# Copyright (c) 2024-2026 Lucas Leão
# TinyConformal - A small toolbox for conformal prediction
# Licensed under the MIT License

import numpy as np
import pandas as pd
from sklearn.base import BaseEstimator, RegressorMixin
from typing import Optional, Tuple, List, Dict
from abc import abstractmethod
import inspect
import re


class BaseConformalTimeSeriesRegressor(RegressorMixin, BaseEstimator):
    """
    BaseConformalTimeSeriesRegressor

    Multi-Step Conformal Distribution Regressor for Time Series.

    Applies conformal prediction over multi-step horizons for Nixtla-style
    estimators (MLForecast or StatsForecast) using sequential backtesting
    to build empirical nonconformity scores (signed residuals).

    Notes:
    -----
    The conformal distribution approach captures prediction interval bounds by working
    directly with empirical signed residuals defined as:
        residual = y_hat - y_true

    By computing low and high empirical quantiles (q_low, q_high) of these residuals across
    calibration windows, the prediction bounds are derived by inverting the nonconformity score:\n
        lower_bound = y_hat - q_high\n
        upper_bound = y_hat - q_low

    This directly adjusts the point forecast for asymmetric bias and variance per horizon step.
    """

    def __init__(
        self,
        learner: BaseEstimator,
        horizon: int,
        n_windows: int = 10,
        alpha: float = 0.05,
        id_col: str = "unique_id",
        time_col: str = "ds",
        target_col: str = "y",
    ):
        """
        Initializes the time series conformal regressor with a Nixtla learner and calibration parameters.

        Parameters:
        ----------
        learner : BaseEstimator
            Unfitted base estimator adhering to the Nixtla interface (e.g., MLForecast or StatsForecast).
        horizon : int
            Forecast horizon step count (H).
        n_windows : int, default=10
            Number of backtesting windows used to extract calibration residuals.
        alpha : float, default=0.05
            Significance level applied in the regressor (target coverage = 1 - alpha).
        id_col : str, default="unique_id"
            Column name representing the unique identifier for each time series.
        time_col : str, default="ds"
            Column name representing time or timestamp steps.
        target_col : str, default="y"
            Column name representing the target variable.

        Attributes:
        ----------
        learner : BaseEstimator
            The base learner employed for time series forecasting.
        horizon : int
            Forecast horizon step count (H).
        n_windows : int
            Number of backtesting windows.
        alpha : float
            Significance level applied in the regressor.
        id_col : str
            Identifier column name.
        time_col : str
            Time column name.
        target_col : str
            Target column name.
        model_col_ : str, default=None
            Inferred column name generated by the base model prediction output.
        exog_cols_ : list, default=None
            List of detected exogenous column names.
        ncscores_ : dict of array-like, default=None
            Dictionary storing nonconformity scores (residuals) per model across calibration windows.
        n : int, default=0
            Total number of calibration trajectories extracted across windows and series.
        """
        self.learner = learner
        self.h = horizon
        self.n_windows = n_windows
        self.id_col = id_col
        self.alpha = alpha
        self.time_col = time_col
        self.target_col = target_col
        self.horizon = horizon

        self.model_col_ = None
        self.exog_cols_ = []
        self.ncscores_ = None
        self.n = 0

    @abstractmethod
    def _generate_residuals(
        self, preds_val: np.ndarray, y_val_arr: np.ndarray
    ) -> np.ndarray:
        """
        Computes nonconformity scores or residuals from predictions and true targets.
        To be implemented by subclasses.
        """
        pass

    @abstractmethod
    def fit(self, df: pd.DataFrame, *args, **kwargs):
        """
        Fits the conformal model to the time series dataset.
        To be implemented by subclasses.
        """
        pass

    @abstractmethod
    def predict_interval(self, *args, **kwargs) -> np.ndarray:
        """
        Generate prediction intervals for the input data.
        To be implemented by subclasses.
        """
        pass

    def _compute_qhat(self, ncscore: np.ndarray, q_level: float, axis: int = None):
        """
        Compute the q-hat quantile value based on nonconformity scores and the quantile level.
        """
        return np.quantile(ncscore, q_level, method="higher", axis=axis)

    def _infer_model_cols(self, df: pd.DataFrame) -> List[str]:
        """
        Dynamically infers model prediction columns from the output DataFrame.
        """
        if self.model_col_ is not None:
            return (
                [self.model_col_]
                if isinstance(self.model_col_, str)
                else self.model_col_
            )

        excluded = {self.id_col, self.time_col, *self.exog_cols_}
        model_cols = [c for c in df.columns if c not in excluded]

        if not model_cols:
            raise ValueError(
                "Could not infer any prediction model column from the returned DataFrame."
            )
        return model_cols

    def _get_alpha(self, alpha: Optional[float] = None) -> float:
        """Helper to retrieve the active significance level (alpha)."""
        return alpha if alpha is not None else self.alpha

    def _get_horizon(self, h: Optional[float] = None) -> float:
        """Helper to retrieve and validate the forecast horizon."""
        h = h if h is not None else self.horizon
        if h > self.horizon:
            raise ValueError(
                f"Requested forecast horizon h={h} exceeds fitted calibration horizon ({self.horizon})."
            )
        return h

    def _invoke(self, method, **kwargs):
        """
        Executes a callable (fit, predict, cross_validation) injecting only
        the parameters accepted by its signature.
        """
        sig = inspect.signature(method)
        has_var_kw = any(
            p.kind == inspect.Parameter.VAR_KEYWORD for p in sig.parameters.values()
        )

        if has_var_kw:
            filtered = {k: v for k, v in kwargs.items() if v is not None}
        else:
            filtered = {
                k: v for k, v in kwargs.items() if k in sig.parameters and v is not None
            }

        return method(**filtered)

    def _coverage_rate(
        self, y_true: np.ndarray, lower: np.ndarray, upper: np.ndarray
    ) -> float:
        """
        Evaluate empirical coverage of prediction intervals.
        """
        coverages = (y_true >= lower) & (y_true <= upper)
        return float(np.mean(coverages))

    def _interval_width_mean(self, lower: np.ndarray, upper: np.ndarray) -> float:
        """
        Calculates the mean width of the prediction intervals.
        """
        widths = upper - lower
        return float(np.mean(widths))

    def _mwi_score(
        self,
        y_true: np.ndarray,
        lower: np.ndarray,
        upper: np.ndarray,
        alpha: float,
    ) -> float:
        """
        Calculate the Winkler interval score for prediction intervals.

        If the observation falls outside the prediction interval, the score increases
        with the distance from the interval bounds.

        If the observation falls inside the prediction interval, the score depends on
        the width of the interval (narrower intervals are better).

        Parameters:
        ----------
        y_true : np.ndarray
            True target values.
        lower : np.ndarray
            Lower bounds of prediction intervals.
        upper : np.ndarray
            Upper bounds of prediction intervals.
        alpha : float
            Significance level, where (1 - alpha) is the desired coverage.

        Returns:
        -------
        float
            The mean Winkler interval score.
        """
        width = upper - lower
        penalty_lower = (2.0 / alpha) * (lower - y_true) * (y_true < lower)
        penalty_upper = (2.0 / alpha) * (y_true - upper) * (y_true > upper)
        return float(np.mean(width + penalty_lower + penalty_upper))

    def _extract_predictions(self, fcst_df: pd.DataFrame) -> np.ndarray:
        """
        Pivots Nixtla long-format DataFrame predictions into a 2D NumPy array.
        Ensures strict row and column alignment sorting.
        """
        if self.model_col_ is None:
            model_cols = [
                c for c in fcst_df.columns if c not in [self.id_col, self.time_col]
            ]
            if not model_cols:
                raise ValueError(
                    "No prediction model column was detected in the model output DataFrame."
                )
            self.model_col_ = model_cols[0]

        pivoted = fcst_df.pivot(
            index=self.id_col, columns=self.time_col, values=self.model_col_
        )
        pivoted = pivoted.sort_index(axis=0).sort_index(axis=1)
        return pivoted.values

    def _extract_target(self, target_df: pd.DataFrame) -> np.ndarray:
        """
        Pivots ground-truth DataFrames into a 2D NumPy array (n_series, horizon).
        Ensures strict row and column alignment sorting matching predictions.
        """
        pivoted = target_df.pivot(
            index=self.id_col, columns=self.time_col, values=self.target_col
        )
        pivoted = pivoted.sort_index(axis=0).sort_index(axis=1)
        return pivoted.values

    def _validate_columns(self, df: pd.DataFrame):
        """
        Validates presence of required structural columns in input DataFrames.
        """
        required_cols = [self.id_col, self.time_col, self.target_col]
        missing = [col for col in required_cols if col not in df.columns]
        if missing:
            raise ValueError(
                f"The following required columns are missing from the DataFrame: {missing}"
            )

    def _generate_residuals(self, y_hat: np.ndarray, y_true: np.ndarray) -> np.ndarray:
        """
        Computes nonconformity scores (signed residuals) via conformal distribution:
            residual = y_hat - y_true
        """
        return y_hat - y_true

    def fit(
        self,
        df: pd.DataFrame,
        step_size: int = None,
        static_features: list = None,
    ):
        """
        Fits the conformal regressor by extracting nonconformity scores across backtest
        windows and training the final base learner on the complete dataset.

        Parameters:
        ----------
        df : pd.DataFrame
            The target and feature time series dataset.
        step_size : int, optional
            Step size between calibration windows. If None, defaults to `self.horizon`.
        static_features : list, optional
            List of static feature column names passed directly to the base learner.

        Returns:
        -------
        self : ConformalDistributionTimeSeriesRegressor
            Fitted instance of the conformal regressor.
        """
        self._validate_columns(df)

        self.exog_cols_ = [
            col
            for col in df.columns
            if col not in (self.id_col, self.time_col, self.target_col)
        ]

        residuals_by_model = self._sequential_backtesting(
            df,
            step_size=step_size,
            static_features=static_features,
        )

        self.ncscores_ = {
            model: np.vstack(res_list) for model, res_list in residuals_by_model.items()
        }
        if not self.ncscores_:
            raise RuntimeError(
                f"No nonconformity scores were extracted during backtesting. "
                f"Verify that 'n_windows' ({self.n_windows}) and 'horizon' ({self.horizon}) "
                f"are compatible with the time series length."
            )

        first_model = next(iter(self.ncscores_))
        self.n = len(self.ncscores_[first_model])

        self._invoke(
            self.learner.fit,
            df=df,
            id_col=self.id_col,
            time_col=self.time_col,
            target_col=self.target_col,
            static_features=static_features,
        )

        return self

    def _sample_correction(self, alpha: float):
        """
        Computes finite-sample quantile adjustment for exact coverage bounds.
        """
        n = self.n
        low_q = max(0.0, alpha / 2.0 - 1.0 / (2.0 * n))
        high_q = min(1.0, 1.0 - alpha / 2.0 + 1.0 / (2.0 * n))
        return low_q, high_q

    def _predict_raw(
        self,
        h: Optional[int] = None,
        X_df: Optional[pd.DataFrame] = None,
    ) -> np.ndarray:
        """
        Generates base model point predictions from Nixtla estimator into standard ndarray.
        """
        h = self._get_horizon(h)

        preds_df = self._invoke(
            self.learner.predict,
            h=h,
            X_df=X_df,
        )
        return self._extract_predictions(preds_df)

    def _compute_bounds(
        self,
        y_hat: np.ndarray,
        model_name: str,
        h: int,
        n_series: int,
        alpha: Optional[float] = None,
    ) -> Tuple[np.ndarray, np.ndarray]:
        """
        Computes lower and upper conformal prediction bounds over 1D prediction vectors.

        Parameters:
        ----------
        y_hat : np.ndarray
            Flattened array of point predictions for a single forecasting model.
        model_name : str
            Identifier name of the model being processed.
        h : int
            Forecast horizon step count.
        n_series : int
            Total number of distinct time series being forecast.
        alpha : float, optional
            Significance level for prediction intervals. If None, default alpha is used.

        Returns:
        -------
        lower_bound : np.ndarray
            Flattened array containing the lower conformal prediction bounds.
        upper_bound : np.ndarray
            Flattened array containing the upper conformal prediction bounds.

        Notes:
        ------
        Calculation Logic and Step-by-Step Bounds Generation:
        1. Quantile Adjustment: Given significance level alpha and calibration count n,
           finite-sample adjusted quantiles low_q and high_q are computed as:\n
               low_q = max(0.0, alpha / 2.0 - 1.0 / (2.0 * n))\n
               high_q = min(1.0, 1.0 - alpha / 2.0 + 1.0 / (2.0 * n))

        2. Empirical Residual Quantiles: Nonconformity scores (residuals = y_hat - y_true)
           sliced to horizon h yield per-step empirical residual thresholds q_low_h and q_high_h
           along axis 0.

        3. Array Tiling: Since point predictions y_hat are flattened across series, threshold
           vectors of size h are repeated n_series times using `np.tile(q_threshold, n_series)`.

        4. Inversion Formula: The prediction bounds invert the nonconformity definition:\n
               lower_bound = y_hat - q_high_tiled\n
               upper_bound = y_hat - q_low_tiled
        """
        alpha = self._get_alpha(alpha)
        low_q, high_q = self._sample_correction(alpha)
        ncscore = self.ncscores_[model_name]
        ncscore_sliced = ncscore[:, :h]
        q_low_h = self._compute_qhat(ncscore_sliced, low_q, axis=0)
        q_high_h = self._compute_qhat(ncscore_sliced, high_q, axis=0)

        q_low_tiled = np.tile(q_low_h, n_series)
        q_high_tiled = np.tile(q_high_h, n_series)

        lower_bound = y_hat - q_high_tiled
        upper_bound = y_hat - q_low_tiled

        return lower_bound, upper_bound

    def predict_interval(
        self,
        h: Optional[int] = None,
        X_df: Optional[pd.DataFrame] = None,
        alpha: float = None,
    ) -> pd.DataFrame:
        """
        Generates prediction intervals [lower, upper] appended directly to Nixtla prediction DataFrames.

        Parameters:
        ----------
        h : int, optional
            Forecast horizon step count. If None, defaults to `self.horizon`.
        X_df : pd.DataFrame, optional
            Exogenous features DataFrame for future steps (required if exogenous columns were fitted).
        alpha : float, optional
            Significance level for prediction intervals. If None, defaults to `self.alpha`.

        Returns:
        -------
        pred_df : pd.DataFrame
            Long-format DataFrame containing point predictions along with generated lower
            and upper bound columns named `<model>-lo-<level>` and `<model>-hi-<level>`.
        """
        h = self._get_horizon(h)

        pred_df = (
            self._invoke(
                self.learner.predict,
                h=h,
                X_df=X_df,
            )
            .sort_values(by=[self.id_col, self.time_col])
            .reset_index(drop=True)
        )
        model_cols = self._infer_model_cols(pred_df)

        for model in model_cols:
            y_hat = pred_df[model].to_numpy()
            n_series = pred_df[self.id_col].nunique()

            lower_bound, upper_bound = self._compute_bounds(
                y_hat=y_hat,
                model_name=model,
                h=h,
                n_series=n_series,
                alpha=alpha,
            )
            eff_alpha = self._get_alpha(alpha)
            level = int(round((1 - eff_alpha) * 100))

            pred_df[f"{model}-lo-{level}"] = lower_bound
            pred_df[f"{model}-hi-{level}"] = upper_bound

        return pred_df

    def evaluate(
        self,
        df_test: pd.DataFrame,
        h: Optional[int] = None,
        alpha: Optional[float] = None,
    ) -> pd.DataFrame:
        """
        Evaluate the performance of the regressor on the given dataset.

        Parameters:
        ----------
        df_test : pd.DataFrame
            Evaluation dataset containing input features and target values.
        h : int, optional
            Forecast horizon step count. If None, the default fitted horizon is used.
        alpha : float, optional
            Significance level for prediction intervals. If None, default alpha is used.

        Returns:
        -------
        pd.DataFrame
            A DataFrame containing the evaluation metrics for each model and level:
            - "model" (str): Name of the evaluated model.
            - "level" (str): Coverage percentage string (e.g., '95%').
            - "alpha" (float): The significance level used for evaluation.
            - "coverage_rate" (float): The coverage rate of the prediction intervals.
            - "interval_width_mean" (float): The mean width of the prediction intervals.
            - "mwis" (float): The Mean Weighted Interval Score (MWIS).
            - "mae" (float): The Mean Absolute Error (MAE) of the predictions.
            - "mbe" (float): The Mean Bias Error (MBE) of the predictions.
            - "mse" (float): The Mean Squared Error (MSE) of the predictions.
        """
        alpha = self._get_alpha(alpha)
        eval_df = self.predict_interval(X_df=df_test, h=h, alpha=alpha)

        eval_df = eval_df.merge(
            df_test[[self.id_col, self.time_col, self.target_col]],
            on=[self.id_col, self.time_col],
            how="inner",
        )
        y_true = eval_df[self.target_col].to_numpy()

        BOUND_PATTERN = re.compile(
            r"^(?P<model>.+)-lo-(?P<level>\d+)(?P<cqr>-(?:cqr|CQR))?$"
        )

        records = []

        def rounded(value):
            return np.round(value, 3)

        for col in eval_df.columns:
            match = BOUND_PATTERN.match(col)

            if not match:
                continue

            base_model = match.group("model")
            level_str = match.group("level")
            has_cqr = bool(match.group("cqr"))

            cqr_suffix = match.group("cqr") if has_cqr else ""
            hi_col = f"{base_model}-hi-{level_str}{cqr_suffix}"

            if hi_col not in eval_df.columns:
                continue

            lower = eval_df[col].to_numpy()
            upper = eval_df[hi_col].to_numpy()

            model_name = f"{base_model}-cqr" if has_cqr else base_model

            records.append(
                {
                    "model": model_name,
                    "level": f"{level_str}%",
                    "alpha": alpha,
                    "coverage_rate": rounded(self._coverage_rate(y_true, lower, upper)),
                    "interval_width_mean": rounded(
                        self._interval_width_mean(lower, upper)
                    ),
                    "mwis": rounded(self._mwi_score(y_true, lower, upper, alpha)),
                }
            )

        return (
            pd.DataFrame(records)
            .sort_values(by=["model", "level"])
            .reset_index(drop=True)
        )
