# Copyright (c) 2024-2026 Lucas Leão
# TinyConformal - A small toolbox for conformal prediction
# Licensed under the MIT License

import inspect
import re
from abc import abstractmethod

import numpy as np
import pandas as pd
from joblib import Parallel, delayed
from sklearn.base import BaseEstimator, RegressorMixin

from tinyconformal.core import conformal as core_conformal
from tinyconformal.core.quantiles import (
    temporal_decay_weights,
    validate_alpha,
    weighted_quantile,
)
from tinyconformal.utils.imports import requires_extra


class BaseConformalTimeSeriesRegressor(RegressorMixin, BaseEstimator):
    """
    BaseConformalTimeSeriesRegressor

    Multi-Step Conformal Distribution Regressor for Time Series.

    Applies conformal prediction over multi-step horizons for Nixtla-style
    estimators (MLForecast or StatsForecast) using sequential backtesting
    to build empirical nonconformity scores (signed residuals).

    Notes:
    -----
    The conformal distribution approach captures prediction interval bounds by working
    directly with empirical signed residuals defined as:
        residual = y_hat - y_true

    By computing low and high empirical quantiles (q_low, q_high) of these residuals across
    calibration windows, the prediction bounds are derived by inverting the nonconformity score:\n
        lower_bound = y_hat - q_high\n
        upper_bound = y_hat - q_low

    This directly adjusts the point forecast for asymmetric bias and variance per horizon step.
    """

    def __init__(
        self,
        learner: BaseEstimator,
        horizon: int,
        n_windows: int = 10,
        nexcp: bool = False,
        decay: float = 0.99,
        weighted_refit: bool = True,
        id_col: str = "unique_id",
        time_col: str = "ds",
        target_col: str = "y",
    ):
        """
        Initializes the time series conformal regressor with a Nixtla learner and calibration parameters.

        Parameters:
        ----------
        learner : BaseEstimator
            Unfitted base estimator adhering to the Nixtla interface (e.g., MLForecast or StatsForecast).
        horizon : int
            Forecast horizon step count (H).
        n_windows : int, default=10
            Number of backtesting windows used to extract calibration residuals.
        nexcp : bool, default=False
            Whether to weight calibration windows by exponential recency decay.
        decay : float, default=0.99
            Decay factor in ``(0, 1)`` used when ``nexcp=True``. The most
            recent observations and calibration windows receive the most weight.
        weighted_refit : bool, default=True
            Whether to pass recency weights to ``learner.fit`` through
            ``weight_col`` when ``nexcp=True``. Has no effect otherwise.
        id_col : str, default="unique_id"
            Column name representing the unique identifier for each time series.
        time_col : str, default="ds"
            Column name representing time or timestamp steps.
        target_col : str, default="y"
            Column name representing the target variable.

        Attributes:
        ----------
        learner : BaseEstimator
            The base learner employed for time series forecasting.
        horizon : int
            Forecast horizon step count (H).
        n_windows : int
            Number of backtesting windows.
        nexcp : bool
            Whether exponentially decayed calibration weights are enabled.
        decay : float
            Exponential recency-decay factor.
        weighted_refit : bool
            Whether recency weights are also used while fitting the learner.
        id_col : str
            Identifier column name.
        time_col : str
            Time column name.
        target_col : str
            Target column name.
        model_col_ : str, default=None
            Inferred column name generated by the base model prediction output.
        exog_cols_ : list, default=None
            List of detected exogenous column names.
        ncscores_ : dict, default=None
            Fitted nonconformity scores. Subclasses may store pooled arrays or
            dictionaries of per-series arrays.
        n : int, default=0
            Number of scores used by one fitted calibration distribution.
        """
        self.learner = learner
        self.h = horizon
        self.n_windows = n_windows
        self.nexcp = nexcp
        self.decay = decay
        self.weighted_refit = weighted_refit
        self.id_col = id_col
        self.time_col = time_col
        self.target_col = target_col
        self.horizon = horizon

        self.model_col_ = None
        self.exog_cols_ = []
        self.static_features_ = []
        self.ncscores_ = None
        self.n = 0
        self._quantile_warning_registry = set()

    @abstractmethod
    def _generate_residuals(
        self, preds_val: np.ndarray, y_val_arr: np.ndarray
    ) -> np.ndarray:
        """
        Computes nonconformity scores or residuals from predictions and true targets.
        To be implemented by subclasses.
        """

    @abstractmethod
    def _prepare_and_validate_steps(
        self, df: pd.DataFrame, *args, **kwargs
    ) -> tuple[np.ndarray, int, int]:
        """Prepares time steps, validates time series length, and returns initial metrics."""

    @abstractmethod
    def _split_train_val_window(
        self,
        df: pd.DataFrame,
        *args,
        **kwargs,
    ) -> tuple[pd.DataFrame, pd.DataFrame]:
        """Slices the dataframe into training and validation sets for a specific window index."""

    @abstractmethod
    def _fit_predict_window(
        self,
        df: pd.DataFrame,
        *args,
        **kwargs,
    ) -> pd.DataFrame:
        """Clones the learner, fits it on the training window, and predicts the validation window."""

    @abstractmethod
    def _compute_window_residuals(
        self,
        df: pd.DataFrame,
        *args,
        **kwargs,
    ) -> None:
        """Calculates nonconformity scores for the predictions and updates the residuals dictionary."""

    @abstractmethod
    def predict_interval(self, *args, **kwargs) -> pd.DataFrame:
        """
        Generate prediction intervals for the input data.
        To be implemented by subclasses.
        """

    @abstractmethod
    def evaluate(self, *args, **kwargs) -> pd.DataFrame:
        """Evaluate predictions according to the subclass interval semantics."""

    def _compute_qhat(
        self, ncscore: np.ndarray, q_level: float, axis: int | None = None
    ):
        """
        Compute the q-hat quantile value based on nonconformity scores and the quantile level.
        """
        if not self.nexcp:
            return np.quantile(ncscore, q_level, method="higher", axis=axis)
        weights = temporal_decay_weights(np.asarray(ncscore).shape[0], self.decay)
        return weighted_quantile(ncscore, q_level, weights, axis=axis)

    def _validate_nexcp(self) -> None:
        """Validate shared NexCP-style temporal weighting parameters."""
        if not isinstance(self.nexcp, (bool, np.bool_)):
            raise TypeError("nexcp must be a boolean.")
        if not isinstance(self.weighted_refit, (bool, np.bool_)):
            raise TypeError("weighted_refit must be a boolean.")
        temporal_decay_weights(1, self.decay)

    @staticmethod
    def _accepts_parameter(method, parameter: str) -> bool:
        signature = inspect.signature(method)
        return parameter in signature.parameters or any(
            item.kind == inspect.Parameter.VAR_KEYWORD
            for item in signature.parameters.values()
        )

    def _fit_forecaster(self, learner, df, static_features=None) -> None:
        """Fit a Nixtla learner, optionally applying NexCP recency weights."""
        fit_df = df
        weight_col = None
        if self.nexcp and self.weighted_refit:
            if not self._accepts_parameter(learner.fit, "weight_col"):
                raise TypeError(
                    f"{type(learner).__name__}.fit must accept weight_col when "
                    "nexcp=True and weighted_refit=True."
                )
            weight_col = "_tinyconformal_weight"
            if weight_col in df.columns:
                raise ValueError(f"Training data already contains '{weight_col}'.")
            times = np.sort(df[self.time_col].unique())
            weights = temporal_decay_weights(len(times), self.decay)
            time_weights = dict(zip(times, weights))
            fit_df = df.copy()
            fit_df[weight_col] = fit_df[self.time_col].map(time_weights)
        self._invoke(
            learner.fit,
            df=fit_df,
            id_col=self.id_col,
            time_col=self.time_col,
            target_col=self.target_col,
            static_features=static_features,
            weight_col=weight_col,
        )

    def _infer_model_cols(self, df: pd.DataFrame) -> list[str]:
        """
        Dynamically infers model prediction columns from the output DataFrame.
        """
        if self.model_col_ is not None:
            return (
                [self.model_col_]
                if isinstance(self.model_col_, str)
                else self.model_col_
            )

        excluded = {self.id_col, self.time_col, *self.exog_cols_}
        model_cols = [c for c in df.columns if c not in excluded]

        if not model_cols:
            raise ValueError(
                "Could not infer any prediction model column from the returned DataFrame."
            )
        return model_cols

    @staticmethod
    def _validate_alpha(alpha: float) -> float:
        """Validate and normalize a concrete significance level."""
        return validate_alpha(alpha)

    def _validate_fit_configuration(self) -> None:
        """Validate subclass-specific calibration configuration before fitting."""
        self._validate_nexcp()

    def _get_horizon(self, h: int | None = None) -> int:
        """Helper to retrieve and validate the forecast horizon."""
        h = h if h is not None else self.horizon
        if not isinstance(h, (int, np.integer)) or isinstance(h, bool) or h <= 0:
            raise ValueError("Forecast horizon h must be a positive integer.")
        if h > self.horizon:
            raise ValueError(
                f"Requested forecast horizon h={h} exceeds fitted calibration horizon ({self.horizon})."
            )
        return int(h)

    def _check_is_fitted(self) -> None:
        """Raise a clear error when prediction is attempted before calibration."""
        if not self.ncscores_ or self.n <= 0:
            raise RuntimeError(
                "This conformal regressor must be fitted before prediction."
            )

    def _prediction_features(self, df: pd.DataFrame) -> pd.DataFrame | None:
        """Return only the columns accepted as future exogenous input."""
        if not self.exog_cols_:
            return None
        required = [self.id_col, self.time_col, *self.exog_cols_]
        missing = [column for column in required if column not in df.columns]
        if missing:
            raise ValueError(
                f"The following future feature columns are missing: {missing}"
            )
        return df[required].copy()

    def _validate_prediction_features(
        self, X_df: pd.DataFrame | None, h: int
    ) -> pd.DataFrame | None:
        """Validate and normalize explicitly supplied future dynamic features."""
        if X_df is None:
            return None

        required = [self.id_col, self.time_col, *self.exog_cols_]
        missing = [column for column in required if column not in X_df.columns]
        if missing:
            raise ValueError(
                f"The following future feature columns are missing: {missing}"
            )
        self._validate_prediction_panel(X_df, h)
        return X_df[required].copy()

    def _merge_predictions_with_targets(
        self, pred_df: pd.DataFrame, target_df: pd.DataFrame
    ) -> pd.DataFrame:
        """Attach targets while preserving exactly one match per prediction row."""
        keys = [self.id_col, self.time_col]
        required = [*keys, self.target_col]
        missing = [column for column in required if column not in target_df.columns]
        if missing:
            raise ValueError(
                f"The evaluation DataFrame is missing required columns: {missing}"
            )
        if target_df.duplicated(keys).any():
            raise ValueError(
                "The evaluation DataFrame must contain at most one target per "
                "identifier and time."
            )

        merged = pred_df.merge(
            target_df[required], on=keys, how="left", validate="one_to_one"
        )
        if merged[self.target_col].isna().any():
            raise ValueError(
                "The evaluation DataFrame must contain a target for every "
                "prediction row."
            )
        return merged

    def _validate_prediction_panel(self, pred_df: pd.DataFrame, h: int) -> int:
        """Validate that forecasts form a balanced series-by-horizon panel."""
        required = [self.id_col, self.time_col]
        missing = [column for column in required if column not in pred_df.columns]
        if missing:
            raise ValueError(
                f"The forecast output is missing structural columns: {missing}"
            )
        if pred_df.duplicated(required).any():
            raise ValueError(
                "Forecast output must contain exactly one row per identifier and time."
            )

        counts = pred_df.groupby(self.id_col, sort=False)[self.time_col].size()
        if counts.empty or not counts.eq(h).all():
            raise ValueError(
                f"Forecast output must contain exactly {h} rows for every series."
            )

        time_grids = pred_df.groupby(self.id_col, sort=False)[self.time_col].apply(
            lambda values: tuple(sorted(values))
        )
        if time_grids.nunique() != 1:
            raise ValueError(
                "Forecast output must use the same horizon timestamps for every series."
            )
        return len(counts)

    def _pivot_panel(self, df: pd.DataFrame, values: str | list[str]) -> pd.DataFrame:
        """Pivot a long-format panel and deterministically order both axes."""
        return (
            df.pivot(index=self.id_col, columns=self.time_col, values=values)
            .sort_index(axis=0)
            .sort_index(axis=1)
        )

    def _extract_target_panel(
        self, val_df: pd.DataFrame, n_series: int
    ) -> tuple[pd.DataFrame, np.ndarray]:
        """Build and validate the target panel for one calibration window."""
        target_pivot = self._pivot_panel(val_df, self.target_col)
        y_true = target_pivot.to_numpy()
        if y_true.shape != (n_series, self.horizon) or np.isnan(y_true).any():
            raise ValueError(
                "Each series must contain exactly one target value for every "
                "calibration horizon step."
            )
        return target_pivot, y_true

    @staticmethod
    def _validate_calibration_forecasts(
        forecast_index: pd.Index,
        target_pivot: pd.DataFrame,
        *forecast_arrays: np.ndarray,
    ) -> None:
        """Validate forecast arrays against the target calibration panel."""
        if (
            not forecast_index.equals(target_pivot.index)
            or any(array.shape != target_pivot.shape for array in forecast_arrays)
            or any(np.isnan(array).any() for array in forecast_arrays)
        ):
            raise ValueError(
                "Forecast and target rows are not aligned for every series and "
                "calibration horizon step."
            )

    @staticmethod
    def _require_forecast_columns(fcst: pd.DataFrame, columns: tuple[str, ...]) -> None:
        """Raise a descriptive error when configured forecast columns are absent."""
        missing = [column for column in columns if column not in fcst.columns]
        if missing:
            raise KeyError(
                f"Columns {tuple(missing)} were not found in forecast output. "
                f"Available columns: {list(fcst.columns)}"
            )

    def _invoke(self, method, **kwargs):
        """
        Executes a callable (fit, predict, cross_validation) injecting only
        the parameters accepted by its signature.
        """
        sig = inspect.signature(method)
        has_var_kw = any(
            p.kind == inspect.Parameter.VAR_KEYWORD for p in sig.parameters.values()
        )

        if has_var_kw:
            filtered = {k: v for k, v in kwargs.items() if v is not None}
        else:
            filtered = {
                k: v for k, v in kwargs.items() if k in sig.parameters and v is not None
            }

        return method(**filtered)

    def _coverage_rate(
        self, y_true: np.ndarray, lower: np.ndarray, upper: np.ndarray
    ) -> float:
        """
        Evaluate empirical coverage of prediction intervals.
        """
        return core_conformal.coverage_rate(y_true, lower, upper)

    def _interval_width_mean(self, lower: np.ndarray, upper: np.ndarray) -> float:
        """
        Calculates the mean width of the prediction intervals.
        """
        return core_conformal.interval_width_mean(lower, upper)

    def _mwi_score(
        self,
        y_true: np.ndarray,
        lower: np.ndarray,
        upper: np.ndarray,
        alpha: float,
    ) -> float:
        """
        Calculate the Winkler interval score for prediction intervals.

        If the observation falls outside the prediction interval, the score increases
        with the distance from the interval bounds.

        If the observation falls inside the prediction interval, the score depends on
        the width of the interval (narrower intervals are better).

        Parameters:
        ----------
        y_true : np.ndarray
            True target values.
        lower : np.ndarray
            Lower bounds of prediction intervals.
        upper : np.ndarray
            Upper bounds of prediction intervals.
        alpha : float
            Significance level, where (1 - alpha) is the desired coverage.

        Returns:
        -------
        float
            The mean Winkler interval score.
        """
        return core_conformal.mwi_score(y_true, lower, upper, alpha)

    def _interval_metrics(
        self,
        y_true: np.ndarray,
        lower: np.ndarray,
        upper: np.ndarray,
        alpha: float,
    ) -> dict:
        """Compute the standard evaluation metrics for one interval, rounded to 3 decimals."""
        return {
            "coverage_rate": np.round(self._coverage_rate(y_true, lower, upper), 3),
            "interval_width_mean": np.round(self._interval_width_mean(lower, upper), 3),
            "mwis": np.round(self._mwi_score(y_true, lower, upper, alpha), 3),
        }

    def _extract_bound_records(
        self, eval_df: pd.DataFrame, y_true: np.ndarray, alpha: float
    ) -> list[dict]:
        """Build one metrics record per ``<model>-lo-<level>``/``-hi-`` column pair."""
        bound_pattern = re.compile(r"^(?P<model>.+)-lo-(?P<level>\d+(?:\.\d+)?)$")
        records = []
        for column in eval_df.columns:
            match = bound_pattern.match(column)
            if not match:
                continue
            model = match.group("model")
            level = match.group("level")
            high_column = f"{model}-hi-{level}"
            if high_column not in eval_df.columns:
                continue
            lower = eval_df[column].to_numpy()
            upper = eval_df[high_column].to_numpy()
            records.append(
                {
                    "model": model,
                    "level": f"{level}%",
                    "alpha": alpha,
                    **self._interval_metrics(y_true, lower, upper, alpha),
                }
            )
        return records

    def _extract_predictions(self, fcst_df: pd.DataFrame) -> np.ndarray:
        """
        Pivots Nixtla long-format DataFrame predictions into a 2D NumPy array.
        Ensures strict row and column alignment sorting.
        """
        if self.model_col_ is None:
            model_cols = [
                c for c in fcst_df.columns if c not in [self.id_col, self.time_col]
            ]
            if not model_cols:
                raise ValueError(
                    "No prediction model column was detected in the model output DataFrame."
                )
            self.model_col_ = model_cols[0]

        pivoted = fcst_df.pivot(
            index=self.id_col, columns=self.time_col, values=self.model_col_
        )
        pivoted = pivoted.sort_index(axis=0).sort_index(axis=1)
        return pivoted.values

    def _validate_columns(self, df: pd.DataFrame):
        """
        Validates presence of required structural columns in input DataFrames.
        """
        required_cols = [self.id_col, self.time_col, self.target_col]
        missing = [col for col in required_cols if col not in df.columns]
        if missing:
            raise ValueError(
                f"The following required columns are missing from the DataFrame: {missing}"
            )

    def _validate_static_features(
        self, df: pd.DataFrame, static_features: list | None
    ) -> list:
        """Normalize and validate static feature column names."""
        static_features = [] if static_features is None else list(static_features)
        missing = [column for column in static_features if column not in df.columns]
        if missing:
            raise ValueError(
                f"The following static feature columns are missing: {missing}"
            )

        structural = {self.id_col, self.time_col, self.target_col}
        invalid = [column for column in static_features if column in structural]
        if invalid:
            raise ValueError(
                "Structural and target columns cannot be static features: " f"{invalid}"
            )
        return static_features

    def _sequential_backtesting(
        self,
        df: pd.DataFrame,
        step_size: int | None = None,
        static_features: list | None = None,
        n_jobs: int = -1,
    ) -> dict:
        """Executes sequential backtesting across n_windows to extract CQR nonconformity scores."""
        step_size = self.horizon if step_size is None else step_size
        if (
            not isinstance(step_size, (int, np.integer))
            or isinstance(step_size, bool)
            or step_size <= 0
        ):
            raise ValueError("step_size must be a positive integer.")

        time_steps, total_steps, n_series = self._prepare_and_validate_steps(
            df, step_size
        )

        def process_window(w):
            train_df, val_df = self._split_train_val_window(
                df, time_steps, total_steps, w, step_size
            )

            fcst = self._fit_predict_window(train_df, val_df, static_features)
            return fcst, val_df

        results = Parallel(n_jobs=n_jobs)(
            delayed(process_window)(w) for w in reversed(range(self.n_windows))
        )

        residuals_by_model = {}
        for fcst, val_df in results:
            self._compute_window_residuals(fcst, val_df, n_series, residuals_by_model)

        return residuals_by_model

    def _finalize_residuals(
        self,
        residuals_by_model: dict[str, list[np.ndarray]],
        series_ids: list,
    ) -> dict:
        """Convert window-level scores to the fitted score representation.

        Subclasses with conditional calibration can override this hook.  The
        default keeps the historical pooled representation.
        """
        del series_ids
        return {
            model: np.vstack(res_list) for model, res_list in residuals_by_model.items()
        }

    @staticmethod
    def _calibration_size(scores) -> int:
        """Return the sample size used by one fitted calibration distribution."""
        if isinstance(scores, dict):
            if not scores:
                return 0
            sizes = {len(values) for values in scores.values()}
            if len(sizes) != 1:
                raise RuntimeError(
                    "Every series must have the same number of calibration scores."
                )
            return sizes.pop()
        return len(scores)

    @requires_extra("series")
    def fit(
        self,
        df: pd.DataFrame,
        step_size: int | None = None,
        static_features: list | None = None,
        n_jobs: int = -1,
    ):
        """
        Fits the conformal regressor by extracting nonconformity scores across backtest
        windows and training the final base learner on the complete dataset.

        Parameters:
        ----------
        df : pd.DataFrame
            The target and feature time series dataset.
        step_size : int, optional
            Step size between calibration windows. If None, defaults to `self.horizon`.
        static_features : list, optional
            Columns that identify time-invariant properties of each series. They are
            passed to the base learner during fitting and excluded from future
            dynamic exogenous inputs. Every other non-structural column is treated
            as a dynamic exogenous feature.
        n_jobs : int, default=-1
            Number of parallel jobs used to process calibration windows.

        Notes
        -----
        Prediction horizons must not exceed the horizon calibrated here. If the
        requested coverage is unattainable for the finite calibration sample, the
        conformal rank is clipped to the observed scores and a ``RuntimeWarning``
        is emitted.

        Returns:
        -------
        self : MultiStepConformalTimeSeriesRegressor
            Fitted instance of the conformal regressor.
        """

        df = df.sort_values(by=[self.id_col, self.time_col]).reset_index(drop=True)

        self._validate_columns(df)
        self._get_horizon()
        self._validate_fit_configuration()
        if (
            not isinstance(self.n_windows, (int, np.integer))
            or isinstance(self.n_windows, bool)
            or self.n_windows <= 0
        ):
            raise ValueError("n_windows must be a positive integer.")

        self.static_features_ = self._validate_static_features(df, static_features)

        self.exog_cols_ = [
            col
            for col in df.columns
            if col
            not in (
                self.id_col,
                self.time_col,
                self.target_col,
                *self.static_features_,
            )
        ]

        residuals_by_model = self._sequential_backtesting(
            df,
            step_size=step_size,
            static_features=self.static_features_ or None,
            n_jobs=n_jobs,
        )

        series_ids = self._pivot_panel(df, self.target_col).index.tolist()
        self.ncscores_ = self._finalize_residuals(residuals_by_model, series_ids)
        if not self.ncscores_:
            raise RuntimeError(
                f"No nonconformity scores were extracted during backtesting. "
                f"Verify that 'n_windows' ({self.n_windows}) and 'horizon' ({self.horizon}) "
                f"are compatible with the time series length."
            )

        first_model = next(iter(self.ncscores_))
        self.n = self._calibration_size(self.ncscores_[first_model])

        self._fit_forecaster(
            self.learner, df, static_features=self.static_features_ or None
        )

        return self

    def _predict_raw(
        self,
        h: int | None = None,
        X_df: pd.DataFrame | None = None,
    ) -> np.ndarray:
        """
        Generates base model point predictions from Nixtla estimator into standard ndarray.
        """
        h = self._get_horizon(h)
        self._check_is_fitted()

        preds_df = self._invoke(
            self.learner.predict,
            h=h,
            X_df=X_df,
        )
        return self._extract_predictions(preds_df)
