# Copyright (c) 2024-2026 Lucas Leão
# TinyConformal - A small toolbox for conformal prediction
# Licensed under the MIT License

import copy
import re

import numpy as np
import pandas as pd
from sklearn.base import BaseEstimator

from tinyconformal.core.conformal import (
    signed_forecast_residuals,
    signed_residual_bounds,
)
from tinyconformal.core.quantiles import central_conformal_quantile_levels
from tinyconformal.utils.imports import requires_extra

from .base import BaseConformalTimeSeriesRegressor


class ConformalDistributionTimeSeriesRegressor(BaseConformalTimeSeriesRegressor):
    """
    Multi-Step Conformal Distribution Regressor for Time Series.

    Applies conformal prediction over multi-step horizons for Nixtla-style
    estimators (MLForecast or StatsForecast) using sequential backtesting
    to build empirical nonconformity scores (residuals). Calibration quantiles
    are computed independently for every series identifier and horizon; signed
    residuals are not pooled across series.
    """

    def __init__(
        self,
        learner: BaseEstimator,
        horizon: int,
        n_windows: int = 10,
        alpha: float = 0.05,
        nexcp: bool = False,
        decay: float = 0.99,
        weighted_refit: bool = True,
        id_col: str = "unique_id",
        time_col: str = "ds",
        target_col: str = "y",
    ):
        """
        Initializes the time series conformal regressor with a Nixtla learner and calibration parameters.

        Parameters
        ----------
        learner : BaseEstimator
            Unfitted base estimator adhering to the Nixtla interface (e.g., MLForecast or StatsForecast).
        horizon : int
            Forecast horizon H.
        n_windows : int, default=10
            Number of backtesting windows used to extract calibration residuals.
        alpha : float, default=0.05
            Significance level applied in the regressor (target coverage = 1 - alpha).
        nexcp : bool, default=False
            Whether to weight calibration windows by exponential recency decay.
        decay : float, default=0.99
            Decay factor in ``(0, 1)`` used when ``nexcp=True``.
        weighted_refit : bool, default=True
            Whether to pass timestamp-level recency weights to ``learner.fit``
            through ``weight_col`` when ``nexcp=True``.
        id_col : str, default="unique_id"
            Column name representing the unique identifier for each time series.
        time_col : str, default="ds"
            Column name representing time or timestamp steps.
        target_col : str, default="y"
            Column name representing the target variable.

        Attributes
        ----------
        learner : BaseEstimator
            The base learner employed for time series forecasting.
        horizon : int
            Forecast horizon H.
        n_windows : int
            Number of backtesting windows.
        alpha : float
            Significance level.
        nexcp : bool
            Whether exponentially decayed calibration weights are enabled.
        decay : float
            Exponential recency-decay factor.
        weighted_refit : bool
            Whether recency weights are also used while fitting the learner.
        id_col : str
            Identifier column name.
        time_col : str
            Time column name.
        target_col : str
            Target column name.
        model_col : str, default=None
            Inferred column name generated by the base model prediction output.
        exog_cols_ : list
            List of detected exogenous column names.
        ncscore : dict, default=None
            Signed residual matrices keyed by model and then by series identifier.
            Each per-series matrix has shape ``(n_windows, horizon)``.
        n : int, default=0
            Number of calibration windows available for each series and horizon.
        """
        super().__init__(
            learner=learner,
            horizon=horizon,
            n_windows=n_windows,
            nexcp=nexcp,
            decay=decay,
            weighted_refit=weighted_refit,
            id_col=id_col,
            time_col=time_col,
            target_col=target_col,
        )
        self.alpha = alpha

    def _get_alpha(self, alpha: float | None = None) -> float:
        """Resolve an optional override against the MSCP global alpha."""
        return self._validate_alpha(self.alpha if alpha is None else alpha)

    def _validate_fit_configuration(self) -> None:
        """Validate the global MSCP significance level before calibration."""
        self._get_alpha()
        self._validate_nexcp()

    def _generate_residuals(self, y_hat: np.ndarray, y_true: np.ndarray) -> np.ndarray:
        """
        Computes nonconformity scores (residuals) via conformal distribution:
        R_{t,h} = \\hat{y}_{t,h} - y_{t,h}
        """
        return signed_forecast_residuals(y_true, y_hat)

    def _finalize_residuals(
        self,
        residuals_by_model: dict[str, list[np.ndarray]],
        series_ids: list,
    ) -> dict[str, dict[object, np.ndarray]]:
        """Preserve one horizon-wise calibration matrix per series."""
        return {
            model: {
                series_id: np.vstack(
                    [window_scores[row] for window_scores in windows]
                )
                for row, series_id in enumerate(series_ids)
            }
            for model, windows in residuals_by_model.items()
        }

    def _prepare_and_validate_steps(
        self, df: pd.DataFrame, step_size: int | None
    ) -> tuple[np.ndarray, int, int]:
        """Prepares time steps, validates time series length, and returns initial metrics."""
        df = df.sort_values(by=[self.id_col, self.time_col])
        time_steps = np.sort(df[self.time_col].unique())
        total_steps = len(time_steps)
        n_series = df[self.id_col].nunique()

        val_end_idx = total_steps - ((self.n_windows - 1) * step_size)
        val_start_idx = val_end_idx - self.horizon

        if val_start_idx <= 0:
            raise ValueError(
                f"Time series length is too short for the specified n_windows ({self.n_windows}) "
                f"and horizon ({self.horizon})."
            )

        return time_steps, total_steps, n_series

    def _split_train_val_window(
        self,
        df: pd.DataFrame,
        time_steps: np.ndarray,
        total_steps: int,
        w: int,
        step_size: int,
    ) -> tuple[pd.DataFrame, pd.DataFrame]:
        """Calculates cutoffs and splits the dataset for a specific backtesting window."""
        val_end_idx = total_steps - (w * step_size)
        val_start_idx = val_end_idx - self.horizon

        train_cutoff = time_steps[val_start_idx - 1]
        val_cutoff = time_steps[val_end_idx - 1]

        train_df = df[df[self.time_col] <= train_cutoff].copy()
        val_df = df[
            (df[self.time_col] > train_cutoff) & (df[self.time_col] <= val_cutoff)
        ].copy()

        return train_df, val_df

    def _fit_predict_window(
        self,
        train_df: pd.DataFrame,
        val_df: pd.DataFrame,
        static_features: list | None = None,
    ) -> pd.DataFrame:
        """Fits a temporary model and predicts the validation horizon."""
        temp_model = copy.deepcopy(self.learner)

        self._fit_forecaster(temp_model, train_df, static_features=static_features)

        predict_cols = [self.id_col, self.time_col] + self.exog_cols_
        X_val = val_df[predict_cols] if self.exog_cols_ else None

        fcst = self._invoke(
            temp_model.predict,
            h=self.horizon,
            X_df=X_val,
        )

        return fcst

    def _extract_target(self, target_df: pd.DataFrame) -> np.ndarray:
        """
        Pivots ground-truth DataFrames into a 2D NumPy array (n_series, horizon).
        Ensures strict row and column alignment sorting matching predictions.
        """
        return self._pivot_panel(target_df, self.target_col).to_numpy()

    def _compute_window_residuals(
        self,
        fcst: pd.DataFrame,
        val_df: pd.DataFrame,
        n_series: int,
        residuals_by_model: dict[str, list],
    ) -> None:
        """Computes residuals for the predictions and appends them to the tracking dictionary."""
        model_cols = self._infer_model_cols(fcst)
        target_pivot, y_true = self._extract_target_panel(val_df, n_series)

        for model in model_cols:
            forecast_pivot = self._pivot_panel(fcst, model)
            y_hat = forecast_pivot.to_numpy()
            self._validate_calibration_forecasts(
                forecast_pivot.index, target_pivot, y_hat
            )
            residuals_by_model.setdefault(model, []).append(
                self._generate_residuals(y_hat, y_true)
            )

    def _sample_correction(self, alpha: float):
        """Compute equal-tailed finite-sample conformal quantile levels."""
        return central_conformal_quantile_levels(
            self.n,
            alpha,
            warning_registry=self._quantile_warning_registry,
            context=self.__class__.__name__,
        )

    def _compute_bounds(
        self,
        y_hat: np.ndarray,
        model_name: str,
        h: int,
        prediction_ids: np.ndarray,
        alpha: float | None = None,
    ) -> tuple[np.ndarray, np.ndarray]:
        """
        Computes the lower and upper conformal bounds over 1D vectors while
        preserving memory efficiency along the calibration-window axis.
        """
        alpha = self._get_alpha(alpha)
        low_q, high_q = self._sample_correction(alpha)
        scores_by_id = self.ncscores_[model_name]
        missing_ids = sorted(set(prediction_ids) - set(scores_by_id), key=str)
        if missing_ids:
            raise ValueError(
                "No calibration scores are available for forecast identifiers: "
                f"{missing_ids}"
            )

        lower_bound = np.empty_like(y_hat, dtype=float)
        upper_bound = np.empty_like(y_hat, dtype=float)
        for series_id in pd.unique(prediction_ids):
            row_mask = prediction_ids == series_id
            ncscore = scores_by_id[series_id][:, :h]
            q_low_h = self._compute_qhat(ncscore, low_q, axis=0)
            q_high_h = self._compute_qhat(ncscore, high_q, axis=0)
            if row_mask.sum() != h:
                raise ValueError(
                    f"Forecast identifier {series_id!r} must contain exactly {h} rows."
                )
            lower, upper = signed_residual_bounds(
                y_hat[row_mask], q_low_h, q_high_h
            )
            lower_bound[row_mask] = lower
            upper_bound[row_mask] = upper

        return lower_bound, upper_bound

    @staticmethod
    def _coverage_label(alpha: float) -> str:
        """Format percentage coverage without discarding fractional levels."""
        coverage = (1.0 - alpha) * 100.0
        return np.format_float_positional(coverage, precision=12, trim="-")

    @requires_extra("series")
    def predict_interval(
        self,
        h: int | None = None,
        X_df: pd.DataFrame | None = None,
        alpha: float | None = None,
    ) -> pd.DataFrame:
        """
        Generates prediction intervals [lower, upper] for Nixtla inputs.

        Parameters
        ----------
        h : int, optional
            Forecast horizon. Defaults to the calibrated horizon and cannot exceed
            it.
        X_df : pd.DataFrame, optional
            Future dynamic features. When provided, it must include the identifier,
            time, and all dynamic exogenous columns, with exactly ``h`` rows per
            series and a common timestamp grid.
        alpha : float, optional
            Significance level overriding the value configured at initialization.
            Fractional coverage percentages are preserved in output column names;
            for example, ``alpha=0.055`` produces a ``-94.5`` suffix.

        Returns
        -------
        pd.DataFrame
            Point forecasts and lower/upper interval columns for every model.
        """
        h = self._get_horizon(h)
        self._check_is_fitted()
        X_df = self._validate_prediction_features(X_df, h)

        pred_df = (
            self._invoke(
                self.learner.predict,
                h=h,
                X_df=X_df,
            )
            .sort_values(by=[self.id_col, self.time_col])
            .reset_index(drop=True)
        )
        model_cols = self._infer_model_cols(pred_df)
        self._validate_prediction_panel(pred_df, h)

        for model in model_cols:
            if model not in self.ncscores_:
                raise ValueError(
                    f"Model column '{model}' was not present during calibration. "
                    f"Calibrated model columns: {list(self.ncscores_)}"
                )
            y_hat = pred_df[model].to_numpy()

            lower_bound, upper_bound = self._compute_bounds(
                y_hat=y_hat,
                model_name=model,
                h=h,
                prediction_ids=pred_df[self.id_col].to_numpy(),
                alpha=alpha,
            )
            eff_alpha = self._get_alpha(alpha)
            level = self._coverage_label(eff_alpha)

            pred_df[f"{model}-lo-{level}"] = lower_bound
            pred_df[f"{model}-hi-{level}"] = upper_bound

        return pred_df

    @requires_extra("series")
    def evaluate(
        self,
        df_test: pd.DataFrame,
        h: int | None = None,
        alpha: float | None = None,
    ) -> pd.DataFrame:
        """Evaluate MSCP intervals using one global or overridden alpha.

        ``df_test`` must provide exactly one non-missing target for every predicted
        identifier and timestamp. Duplicate or missing matches raise ``ValueError``.
        """
        alpha = self._get_alpha(alpha)
        eval_df = self.predict_interval(
            X_df=self._prediction_features(df_test), h=h, alpha=alpha
        )
        eval_df = self._merge_predictions_with_targets(eval_df, df_test)

        y_true = eval_df[self.target_col].to_numpy()
        bound_pattern = re.compile(r"^(?P<model>.+)-lo-(?P<level>\d+(?:\.\d+)?)$")
        records = []
        for col in eval_df.columns:
            match = bound_pattern.match(col)
            if not match:
                continue

            model = match.group("model")
            level = match.group("level")
            high_col = f"{model}-hi-{level}"
            if high_col not in eval_df.columns:
                continue

            lower = eval_df[col].to_numpy()
            upper = eval_df[high_col].to_numpy()
            records.append(
                {
                    "model": model,
                    "level": f"{level}%",
                    "alpha": alpha,
                    "coverage_rate": np.round(
                        self._coverage_rate(y_true, lower, upper), 3
                    ),
                    "interval_width_mean": np.round(
                        self._interval_width_mean(lower, upper), 3
                    ),
                    "mwis": np.round(self._mwi_score(y_true, lower, upper, alpha), 3),
                }
            )

        return (
            pd.DataFrame(records)
            .sort_values(by=["model", "level"])
            .reset_index(drop=True)
        )
