# Copyright (c) 2024-2026 Lucas Leão
# TinyConformal - A small toolbox for conformal prediction
# Licensed under the MIT License

import numpy as np
import pandas as pd
from sklearn.base import BaseEstimator
from .base import BaseConformalTimeSeriesRegressor
from typing import Optional, Tuple, List, Dict
from tinyconformal.utils.imports import requires_extra
import copy


class ConformalDistributionTimeSeriesRegressor(BaseConformalTimeSeriesRegressor):
    """
    Multi-Step Conformal Distribution Regressor for Time Series.

    Applies conformal prediction over multi-step horizons for Nixtla-style
    estimators (MLForecast or StatsForecast) using sequential backtesting
    to build empirical nonconformity scores (residuals).
    """

    def __init__(
        self,
        learner: BaseEstimator,
        horizon: int,
        n_windows: int = 10,
        alpha: float = 0.05,
        id_col: str = "unique_id",
        time_col: str = "ds",
        target_col: str = "y",
    ):
        """
        Initializes the time series conformal regressor with a Nixtla learner and calibration parameters.

        Parameters
        ----------
        learner : BaseEstimator
            Unfitted base estimator adhering to the Nixtla interface (e.g., MLForecast or StatsForecast).
        horizon : int
            Forecast horizon H.
        n_windows : int, default=10
            Number of backtesting windows used to extract calibration residuals.
        alpha : float, default=0.05
            Significance level applied in the regressor (target coverage = 1 - alpha).
        id_col : str, default="unique_id"
            Column name representing the unique identifier for each time series.
        time_col : str, default="ds"
            Column name representing time or timestamp steps.
        target_col : str, default="y"
            Column name representing the target variable.

        Attributes
        ----------
        learner : BaseEstimator
            The base learner employed for time series forecasting.
        horizon : int
            Forecast horizon H.
        n_windows : int
            Number of backtesting windows.
        alpha : float
            Significance level.
        id_col : str
            Identifier column name.
        time_col : str
            Time column name.
        target_col : str
            Target column name.
        model_col : str, default=None
            Inferred column name generated by the base model prediction output.
        exog_cols_ : list
            List of detected exogenous column names.
        ncscore : array-like, default=None
            Array of nonconformity scores (residuals) of shape (N, horizon).
        n : int, default=0
            Total number of calibration trajectories extracted across windows and series.
        """
        super().__init__(
            learner=learner,
            horizon=horizon,
            n_windows=n_windows,
            alpha=alpha,
            id_col=id_col,
            time_col=time_col,
            target_col=target_col,
        )

    def _validate_columns(self, df: pd.DataFrame):
        """Validates presence of required structural columns in input DataFrames."""
        required_cols = [self.id_col, self.time_col, self.target_col]
        missing = [col for col in required_cols if col not in df.columns]
        if missing:
            raise ValueError(
                f"The following required columns are missing from the DataFrame: {missing}"
            )

    def _generate_residuals(self, y_hat: np.ndarray, y_true: np.ndarray) -> np.ndarray:
        """
        Computes nonconformity scores (residuals) via conformal distribution:
        R_{t,h} = \\hat{y}_{t,h} - y_{t,h}
        """
        return y_hat - y_true

    def _prepare_and_validate_steps(
        self, df: pd.DataFrame, step_size: Optional[int]
    ) -> Tuple[np.ndarray, int, int]:
        """Prepares time steps, validates time series length, and returns initial metrics."""
        df = df.sort_values(by=[self.id_col, self.time_col])
        time_steps = np.sort(df[self.time_col].unique())
        total_steps = len(time_steps)
        n_series = df[self.id_col].nunique()

        val_end_idx = total_steps - ((self.n_windows - 1) * step_size)
        val_start_idx = val_end_idx - self.horizon

        if val_start_idx <= 0:
            raise ValueError(
                f"Time series length is too short for the specified n_windows ({self.n_windows}) "
                f"and horizon ({self.horizon})."
            )

        return time_steps, total_steps, n_series

    def _split_train_val_window(
        self,
        df: pd.DataFrame,
        time_steps: np.ndarray,
        total_steps: int,
        w: int,
        step_size: int,
    ) -> Tuple[pd.DataFrame, pd.DataFrame]:
        """Calculates cutoffs and splits the dataset for a specific backtesting window."""
        val_end_idx = total_steps - (w * step_size)
        val_start_idx = val_end_idx - self.horizon

        train_cutoff = time_steps[val_start_idx - 1]
        val_cutoff = time_steps[val_end_idx - 1]

        train_df = df[df[self.time_col] <= train_cutoff].copy()
        val_df = df[
            (df[self.time_col] > train_cutoff) & (df[self.time_col] <= val_cutoff)
        ].copy()

        return train_df, val_df

    def _fit_predict_window(
        self,
        train_df: pd.DataFrame,
        val_df: pd.DataFrame,
        static_features: Optional[list] = None,
    ) -> pd.DataFrame:
        """Fits a temporary model and predicts the validation horizon."""
        temp_model = copy.deepcopy(self.learner)

        self._invoke(
            temp_model.fit,
            df=train_df,
            id_col=self.id_col,
            time_col=self.time_col,
            target_col=self.target_col,
            static_features=static_features,
        )

        predict_cols = [self.id_col, self.time_col] + self.exog_cols_
        X_val = val_df[predict_cols] if self.exog_cols_ else None

        fcst = self._invoke(
            temp_model.predict,
            h=self.horizon,
            X_df=X_val,
        )

        return fcst

    def _compute_window_residuals(
        self,
        fcst: pd.DataFrame,
        val_df: pd.DataFrame,
        n_series: int,
        residuals_by_model: Dict[str, list],
    ) -> None:
        """Computes residuals for the predictions and appends them to the tracking dictionary."""
        model_cols = self._infer_model_cols(fcst)
        y_true = self._extract_target(val_df)

        for model in model_cols:
            y_hat = fcst[model].to_numpy().reshape(n_series, self.horizon)
            r = self._generate_residuals(y_hat, y_true)

            if model not in residuals_by_model:
                residuals_by_model[model] = []
            residuals_by_model[model].append(r)

    def _sequential_backtesting(
        self,
        df: pd.DataFrame,
        step_size: Optional[int] = None,
        static_features: Optional[list] = None,
    ) -> dict:
        """
        Executes sequential rolling-window backtesting across calibration windows.
        """
        if step_size is None:
            step_size = self.horizon

        time_steps, total_steps, n_series = self._prepare_and_validate_steps(
            df, step_size
        )

        residuals_by_model: Dict[str, list] = {}

        for w in reversed(range(self.n_windows)):
            train_df, val_df = self._split_train_val_window(
                df, time_steps, total_steps, w, step_size
            )

            fcst = self._fit_predict_window(train_df, val_df, static_features)

            self._compute_window_residuals(fcst, val_df, n_series, residuals_by_model)

        return residuals_by_model

    @requires_extra("series")
    def fit(
        self,
        df: pd.DataFrame,
        step_size: int = None,
        static_features: list = None,
    ):
        """
        Fits the conformal regressor by extracting nonconformity scores across backtest
        windows and training the final base learner on the complete dataset.

        Parameters
        ----------
        df : pd.DataFrame
            The target and feature time series dataset.
        step_size : int, optional
            Step size between calibration windows. If None, defaults to `self.horizon`.
        static_features : list, optional
            List of static feature column names passed directly to the base learner.

        Returns
        -------
        self : ConformalDistributionTimeSeriesRegressor
            Fitted instance of the conformal regressor.
        """
        self._validate_columns(df)

        self.exog_cols_ = [
            col
            for col in df.columns
            if col not in (self.id_col, self.time_col, self.target_col)
        ]

        residuals_by_model = self._sequential_backtesting(
            df,
            step_size=step_size,
            static_features=static_features,
        )

        self.ncscores_ = {
            model: np.vstack(res_list) for model, res_list in residuals_by_model.items()
        }
        if not self.ncscores_:
            raise RuntimeError(
                f"No nonconformity scores were extracted during backtesting. "
                f"Verify that 'n_windows' ({self.n_windows}) and 'horizon' ({self.horizon}) "
                f"are compatible with the time series length."
            )

        first_model = next(iter(self.ncscores_))
        self.n = len(self.ncscores_[first_model])

        self._invoke(
            self.learner.fit,
            df=df,
            id_col=self.id_col,
            time_col=self.time_col,
            target_col=self.target_col,
            static_features=static_features,
        )

        return self

    def _sample_correction(self, alpha: float):
        """Computes finite-sample quantile adjustment for exact coverage bounds."""
        n = self.n
        low_q = max(0.0, alpha / 2.0 - 1.0 / (2.0 * n))
        high_q = min(1.0, 1.0 - alpha / 2.0 + 1.0 / (2.0 * n))
        return low_q, high_q

    def _predict_raw(
        self,
        h: Optional[int] = None,
        X_df: Optional[pd.DataFrame] = None,
    ) -> np.ndarray:
        """
        Generates base model point predictions from Nixtla estimator into standard ndarray.
        """
        h = self._get_horizon(h)

        preds_df = self._invoke(
            self.learner.predict,
            h=h,
            X_df=X_df,
        )
        return self._extract_predictions(preds_df)

    def _compute_bounds(
        self,
        y_hat: np.ndarray,
        model_name: str,
        h: int,
        n_series: int,
        alpha: Optional[float] = None,
    ) -> Tuple[np.ndarray, np.ndarray]:
        """
        Calcula os limites inferior e superior conformais sobre vetores 1D
        mantendo a eficiência de memória (eixo das janelas).
        """
        alpha = self._get_alpha(alpha)
        low_q, high_q = self._sample_correction(alpha)
        ncscore = self.ncscores_[model_name]
        ncscore_sliced = ncscore[:, :h]
        q_low_h = self._compute_qhat(ncscore_sliced, low_q, axis=0)
        q_high_h = self._compute_qhat(ncscore_sliced, high_q, axis=0)

        q_low_tiled = np.tile(q_low_h, n_series)
        q_high_tiled = np.tile(q_high_h, n_series)

        lower_bound = y_hat - q_high_tiled
        upper_bound = y_hat - q_low_tiled

        return lower_bound, upper_bound

    @requires_extra("series")
    def predict_interval(
        self,
        h: Optional[int] = None,
        X_df: Optional[pd.DataFrame] = None,
        alpha: float = None,
    ) -> np.ndarray:
        """
        Generates prediction intervals [lower, upper] for Nixtla inputs.

        Returns
        -------
        intervals : ndarray of shape (n_series, horizon, 2)
        """
        h = self._get_horizon(h)

        pred_df = (
            self._invoke(
                self.learner.predict,
                h=h,
                X_df=X_df,
            )
            .sort_values(by=[self.id_col, self.time_col])
            .reset_index(drop=True)
        )
        model_cols = self._infer_model_cols(pred_df)

        for model in model_cols:
            y_hat = pred_df[model].to_numpy()
            n_series = pred_df[self.id_col].nunique()

            lower_bound, upper_bound = self._compute_bounds(
                y_hat=y_hat,
                model_name=model,
                h=h,
                n_series=n_series,
                alpha=alpha,
            )
            eff_alpha = self._get_alpha(alpha)
            level = int(round((1 - eff_alpha) * 100))

            pred_df[f"{model}-lo-{level}"] = lower_bound
            pred_df[f"{model}-hi-{level}"] = upper_bound

        return pred_df
