# Copyright (c) 2024-2026 Lucas Leão
# TinyConformal - A small toolbox for conformal prediction
# Licensed under the MIT License

import copy
import re

import numpy as np
import pandas as pd
from sklearn.base import BaseEstimator

from tinyconformal.utils.imports import requires_extra
from tinyconformal.utils.quantiles import conformal_quantile_level

from .base import BaseConformalTimeSeriesRegressor


class ConformalQuantileTimeSeriesRegressor(BaseConformalTimeSeriesRegressor):
    r"""
    Multi-Step Conformal Quantile Regressor for Time Series (TSCQR).

    Applies Conformalized Quantile Regression (CQR) over multi-step horizons for
    Nixtla-style estimators (e.g., MLForecast or StatsForecast) using sequential
    backtesting to build empirical nonconformity scores across single or multiple
    quantile prediction pairs.

    Column Naming Convention
    ------------------------
    All quantile columns supplied in `intervals` MUST follow the strict pattern:
    - Lower bound: `<model>-lo-<level>` (e.g., `'LGBM-lo-90'`)
    - Upper bound: `<model>-hi-<level>` (e.g., `'LGBM-hi-90'`)

    where `<model>` is the estimator name and `<level>` is an integer representing
    the nominal coverage percentage (e.g., 90 for a 90% prediction interval).

    Output Columns
    --------------
    When calling `predict_interval()`, conformalized lower and upper prediction
    bounds are added as new columns with the `-cqr` suffix attached:
    - `<model>-lo-<level>-cqr`
    - `<model>-hi-<level>-cqr`

    This naming structure allows seamless pattern matching in downstream evaluation
    utilities such as `evaluate()`.

    Parameters
    ----------
    learner : BaseEstimator
        Unfitted base estimator adhering to the Nixtla interface (e.g., MLForecast
        or StatsForecast) configured to generate quantile predictions.
    horizon : int
        Forecast horizon H.
    intervals : tuple or list
        A tuple of column names `(lower_col, upper_col)` or a list of such tuples
        representing quantile prediction pairs generated by the base learner.
        Must strictly follow the `<model>-lo-<level>` and `<model>-hi-<level>`
        naming convention.
    n_windows : int, default=3
        Number of backtesting windows used to extract calibration residuals.
    id_col : str, default="unique_id"
        Column name representing the unique identifier for each time series.
    time_col : str, default="ds"
        Column name representing time or timestamp steps.
    target_col : str, default="y"
        Column name representing the target variable.

    Attributes
    ----------
    learner : BaseEstimator
        The base learner employed for time series forecasting.
    horizon : int
        Forecast horizon H.
    intervals_ : List[Tuple[str, str]]
        Normalized and validated list of quantile column pairs.
    interval_alphas_ : Dict[Tuple[str, str], float]
        Significance level inferred from each pair's coverage suffix. For example,
        columns ending in `-90` use `alpha=0.10`.
    n_windows : int
        Number of backtesting windows.
    alpha : float
        Significance level.
    id_col : str
        Identifier column name.
    time_col : str
        Time column name.
    target_col : str
        Target column name.
    exog_cols_ : list
        List of detected exogenous column names.
    ncscores_ : dict
        Dictionary mapping each quantile pair key (`"low_col:high_col"`) to a 2D numpy
        array of nonconformity scores of shape (N, horizon).
    n : int, default=0
        Total number of calibration trajectories extracted across windows and series.

    Notes
    -----
    - Nonconformity scores are computed via $E_{i,t} = \max(q_{\text{low}} - y, y - q_{\text{high}})$.
    - Finite-sample correction uses order-statistic rank
      $\lceil (n+1)(1-\alpha) \rceil$, mapped exactly to NumPy's ``higher`` quantile.

    Examples
    --------
    >>> import lightgbm as lgb
    >>> from mlforecast import MLForecast
    >>> from tinyconformal.series import ConformalQuantileTimeSeriesRegressor
    >>>
    >>> def create_mlforecast_multiquantile():
    ...     models = {
    ...         "LGBM-lo-90": lgb.LGBMRegressor(objective="quantile", alpha=0.05, random_state=42),
    ...         "LGBM-hi-90": lgb.LGBMRegressor(objective="quantile", alpha=0.95, random_state=42),
    ...         "LGBM-lo-50": lgb.LGBMRegressor(objective="quantile", alpha=0.25, random_state=42),
    ...         "LGBM-hi-50": lgb.LGBMRegressor(objective="quantile", alpha=0.75, random_state=42),
    ...     }
    ...     return MLForecast(
    ...         models=models,
    ...         freq="D",
    ...         lags=[1, 7],
    ...     )
    >>>
    >>> base_mlf = create_mlforecast_multiquantile()
    >>> cqr = ConformalQuantileTimeSeriesRegressor(
    ...     learner=base_mlf,
    ...     horizon=7,
    ...     intervals=[
    ...         ("LGBM-lo-90", "LGBM-hi-90"),
    ...         ("LGBM-lo-50", "LGBM-hi-50"),
    ...     ],
    ...     n_windows=5,
    ... )
    >>> cqr.fit(df)
    >>> predictions = cqr.predict_interval(h=7)
    >>> eval_results = cqr.evaluate(df_test)
    """

    def __init__(
        self,
        learner: BaseEstimator,
        horizon: int,
        intervals: tuple[str, str] | list[tuple[str, str]],
        n_windows: int = 3,
        id_col: str = "unique_id",
        time_col: str = "ds",
        target_col: str = "y",
    ):
        self.intervals = intervals
        self.intervals_, self.interval_alphas_ = self._normalize_intervals(intervals)

        super().__init__(
            learner=learner,
            horizon=horizon,
            n_windows=n_windows,
            id_col=id_col,
            time_col=time_col,
            target_col=target_col,
        )

    def _parse_quantile_pair(self, low_col: str, high_col: str) -> dict[str, str]:
        """
        Validates and extracts metadata from a quantile column pair.

        Raises ValueError if column names do not strictly comply with the
        Nixtla/Conformal pattern '<model>-lo-<level>' and '<model>-hi-<level>'.
        """
        QUANTILE_COL_PATTERN = re.compile(
            r"^(?P<model>.+)-(?P<bound>lo|hi)-(?P<level>\d+)$"
        )

        match_low = QUANTILE_COL_PATTERN.match(low_col)
        match_high = QUANTILE_COL_PATTERN.match(high_col)

        if not match_low or match_low.group("bound") != "lo":
            raise ValueError(
                f"Invalid lower quantile column name: '{low_col}'. "
                f"Expected pattern '<model>-lo-<level>' (e.g., 'LGBM-lo-90')."
            )

        if not match_high or match_high.group("bound") != "hi":
            raise ValueError(
                f"Invalid upper quantile column name: '{high_col}'. "
                f"Expected pattern '<model>-hi-<level>' (e.g., 'LGBM-hi-90')."
            )

        model_low, level_low = match_low.group("model"), match_low.group("level")
        model_high, level_high = match_high.group("model"), match_high.group("level")

        if model_low != model_high:
            raise ValueError(
                f"Model name mismatch in quantile pair: '{model_low}' vs '{model_high}'."
            )

        if level_low != level_high:
            raise ValueError(
                f"Coverage level mismatch in quantile pair: '{level_low}' vs '{level_high}'."
            )

        level = int(level_low)
        if not 0 < level < 100:
            raise ValueError("Coverage level must be an integer between 1 and 99.")

        return {
            "model": model_low,
            "level": level,
        }

    def _normalize_intervals(
        self,
        intervals: tuple[str, str] | list[tuple[str, str]],
    ) -> tuple[
        list[tuple[str, str]],
        dict[tuple[str, str], float],
    ]:
        """Normalize and validate interval pairs."""
        if isinstance(intervals, tuple) and len(intervals) == 2:
            pairs = [intervals]
        elif isinstance(intervals, list) and all(
            isinstance(p, (tuple, list)) and len(p) == 2 for p in intervals
        ):
            pairs = [tuple(p) for p in intervals]
        else:
            raise ValueError(
                "intervals must be a tuple of 2 column names (low, high) "
                "or a list of such tuples."
            )

        if not pairs:
            raise ValueError("intervals must contain at least one quantile pair.")

        alphas = {}
        for low_col, high_col in pairs:
            metadata = self._parse_quantile_pair(low_col, high_col)
            alphas[(low_col, high_col)] = 1.0 - metadata["level"] / 100.0

        return pairs, alphas

    def _sample_correction(self, alpha: float) -> float:
        """Computes finite-sample quantile adjustment level."""
        return conformal_quantile_level(
            self.n,
            alpha,
            warning_registry=self._quantile_warning_registry,
            context=self.__class__.__name__,
        )

    def _generate_residuals(
        self, q_low: np.ndarray, q_high: np.ndarray, y_true: np.ndarray
    ) -> np.ndarray:
        """Computes CQR Nonconformity Scores: E_{i,t} = max(q_low - y, y - q_high)"""
        return np.maximum(q_low - y_true, y_true - q_high)

    def _prepare_and_validate_steps(
        self, df: pd.DataFrame, step_size: int
    ) -> tuple[np.ndarray, int, int]:
        """Validates if the time series has enough steps for the requested backtesting windows."""
        unique_ids = df[self.id_col].unique()
        n_series = len(unique_ids)

        time_steps = np.sort(df[self.time_col].unique())
        total_steps = len(time_steps)

        required_steps = self.horizon + (self.n_windows - 1) * step_size
        if total_steps <= required_steps:
            raise ValueError(
                f"Time series has {total_steps} unique time steps, but "
                f"n_windows={self.n_windows}, horizon={self.horizon}, step_size={step_size} "
                f"requires at least {required_steps + 1} steps."
            )

        return time_steps, total_steps, n_series

    def _split_train_val_window(
        self,
        df: pd.DataFrame,
        time_steps: np.ndarray,
        total_steps: int,
        w: int,
        step_size: int,
    ) -> tuple[pd.DataFrame, pd.DataFrame]:
        """Slices the dataframe into training and validation sets for a specific window index."""
        val_end_idx = total_steps - w * step_size
        val_start_idx = val_end_idx - self.horizon

        cutoff_time = time_steps[val_start_idx - 1]
        val_times = time_steps[val_start_idx:val_end_idx]

        train_mask = df[self.time_col] <= cutoff_time
        val_mask = df[self.time_col].isin(val_times)

        train_df = df[train_mask].reset_index(drop=True)
        val_df = (
            df[val_mask]
            .sort_values(by=[self.id_col, self.time_col])
            .reset_index(drop=True)
        )

        return train_df, val_df

    def _fit_predict_window(
        self,
        train_df: pd.DataFrame,
        val_df: pd.DataFrame,
        static_features: list | None,
    ) -> pd.DataFrame:
        """Clones the learner, fits it on the training window, and predicts the validation window."""
        learner_clone = copy.deepcopy(self.learner)
        self._invoke(
            learner_clone.fit,
            df=train_df,
            id_col=self.id_col,
            time_col=self.time_col,
            target_col=self.target_col,
            static_features=static_features,
        )

        predict_cols = [self.id_col, self.time_col] + self.exog_cols_
        X_val = val_df[predict_cols] if self.exog_cols_ else None

        fcst = (
            self._invoke(
                learner_clone.predict,
                h=self.horizon,
                X_df=X_val,
            )
            .sort_values(by=[self.id_col, self.time_col])
            .reset_index(drop=True)
        )

        return fcst

    def _compute_window_residuals(
        self,
        fcst: pd.DataFrame,
        val_df: pd.DataFrame,
        n_series: int,
        residuals_by_model: dict,
    ) -> None:
        """Calculates nonconformity scores for the predictions and updates the residuals dictionary."""
        target_pivot, y_true = self._extract_target_panel(val_df, n_series)

        for low_col, high_col in self.intervals_:
            self._require_forecast_columns(fcst, (low_col, high_col))
            quantiles = self._pivot_panel(fcst, [low_col, high_col])
            q_low = quantiles[low_col].to_numpy()
            q_high = quantiles[high_col].to_numpy()
            self._validate_calibration_forecasts(
                quantiles.index, target_pivot, q_low, q_high
            )
            if np.any(q_low > q_high):
                raise ValueError(
                    f"Crossing quantiles detected for columns {(low_col, high_col)}."
                )

            pair_key = f"{low_col}:{high_col}"
            residuals_by_model.setdefault(pair_key, []).append(
                self._generate_residuals(q_low, q_high, y_true)
            )

    def _compute_bounds(
        self,
        q_low: np.ndarray,
        q_high: np.ndarray,
        pair_key: str,
        h: int,
        n_series: int,
        alpha: float,
    ) -> tuple[np.ndarray, np.ndarray]:
        """Computes lower and upper conformalized quantile bounds.

        The returned bounds are ``q_low - q_hat`` and ``q_high + q_hat``.
        """
        q_level = self._sample_correction(self._validate_alpha(alpha))

        ncscore = self.ncscores_[pair_key]
        ncscore_sliced = ncscore[:, :h]

        q_hat_h = self._compute_qhat(ncscore_sliced, q_level, axis=0)
        q_hat_tiled = np.tile(q_hat_h, n_series)

        lower_bound = q_low - q_hat_tiled
        upper_bound = q_high + q_hat_tiled

        return lower_bound, upper_bound

    @requires_extra("series")
    def predict_interval(
        self,
        h: int | None = None,
        X_df: pd.DataFrame | None = None,
    ) -> pd.DataFrame:
        """Apply conformal correction to configured quantile pairs.

        Generates calibrated interval columns named `<low_col>-cqr` and `<high_col>-cqr`.

        Parameters
        ----------
        h : Optional[int], default=None
            Forecast horizon. If None, uses the default horizon from the underlying learner.
        X_df : Optional[pd.DataFrame], default=None
            Exogenous features DataFrame for the forecast horizon.

        Returns
        -------
        pd.DataFrame
            DataFrame containing raw base predictions, conformal-calibrated interval bounds
            (`<col>-cqr`).
        """
        h = self._get_horizon(h)
        self._check_is_fitted()

        pred_df = (
            self._invoke(
                self.learner.predict,
                h=h,
                X_df=X_df,
            )
            .sort_values(by=[self.id_col, self.time_col])
            .reset_index(drop=True)
        )

        n_series = self._validate_prediction_panel(pred_df, h)

        for low_col, high_col in self.intervals_:
            q_low = pred_df[low_col].to_numpy()
            q_high = pred_df[high_col].to_numpy()
            if np.any(q_low > q_high):
                raise ValueError(
                    f"Crossing quantiles detected for columns {(low_col, high_col)}."
                )
            pair_key = f"{low_col}:{high_col}"
            interval_alpha = self.interval_alphas_[(low_col, high_col)]

            lower_bound, upper_bound = self._compute_bounds(
                q_low=q_low,
                q_high=q_high,
                pair_key=pair_key,
                h=h,
                n_series=n_series,
                alpha=interval_alpha,
            )

            pred_df[f"{low_col}-cqr"] = lower_bound
            pred_df[f"{high_col}-cqr"] = upper_bound

        return pred_df

    @requires_extra("series")
    def evaluate(
        self,
        df_test: pd.DataFrame,
        h: int | None = None,
    ) -> pd.DataFrame:
        """Evaluate every configured raw and conformalized interval at its own alpha."""
        eval_df = self.predict_interval(X_df=self._prediction_features(df_test), h=h)
        eval_df = eval_df.merge(
            df_test[[self.id_col, self.time_col, self.target_col]],
            on=[self.id_col, self.time_col],
            how="inner",
        )
        if eval_df.empty:
            raise ValueError(
                "No prediction rows matched df_test on the identifier and time columns."
            )

        y_true = eval_df[self.target_col].to_numpy()
        records = []
        for low_col, high_col in self.intervals_:
            metadata = self._parse_quantile_pair(low_col, high_col)
            alpha = self.interval_alphas_[(low_col, high_col)]
            for suffix, model_suffix in (("", ""), ("-cqr", "-cqr")):
                lower = eval_df[f"{low_col}{suffix}"].to_numpy()
                upper = eval_df[f"{high_col}{suffix}"].to_numpy()
                records.append(
                    {
                        "model": f"{metadata['model']}{model_suffix}",
                        "level": f"{metadata['level']}%",
                        "alpha": alpha,
                        "coverage_rate": np.round(
                            self._coverage_rate(y_true, lower, upper), 3
                        ),
                        "interval_width_mean": np.round(
                            self._interval_width_mean(lower, upper), 3
                        ),
                        "mwis": np.round(
                            self._mwi_score(y_true, lower, upper, alpha), 3
                        ),
                    }
                )

        return (
            pd.DataFrame(records)
            .sort_values(by=["model", "level"])
            .reset_index(drop=True)
        )
