# Copyright (c) 2024-2026 Lucas Leão
# TinyConformal - A small toolbox for conformal prediction
# Licensed under the MIT License

from typing import List, Optional, Tuple, Union, Dict
import numpy as np
import pandas as pd
from sklearn.base import BaseEstimator
from .base import BaseConformalTimeSeriesRegressor
import re


class ConformalQuantileTimeSeriesRegressor(BaseConformalTimeSeriesRegressor):
    """
    Multi-Step Conformal Quantile Regressor for Time Series (TSCQR).

    Applies Conformalized Quantile Regression (CQR) over multi-step horizons for
    Nixtla-style estimators (e.g., MLForecast or StatsForecast) using sequential
    backtesting to build empirical nonconformity scores across single or multiple
    quantile prediction pairs.

    Column Naming Convention
    ------------------------
    All quantile columns supplied in `interval_pairs` MUST follow the strict pattern:
    - Lower bound: `<model>-lo-<level>` (e.g., `'LGBM-lo-90'`)
    - Upper bound: `<model>-hi-<level>` (e.g., `'LGBM-hi-90'`)

    where `<model>` is the estimator name and `<level>` is an integer representing
    the nominal coverage percentage (e.g., 90 for a 90% prediction interval).

    Output Columns
    --------------
    When calling `predict_interval()`, conformalized lower and upper prediction
    bounds are added as new columns with the `-cqr` suffix attached:
    - `<model>-lo-<level>-cqr`
    - `<model>-hi-<level>-cqr`

    This naming structure allows seamless pattern matching in downstream evaluation
    utilities such as `evaluate()`.

    Parameters
    ----------
    learner : BaseEstimator
        Unfitted base estimator adhering to the Nixtla interface (e.g., MLForecast
        or StatsForecast) configured to generate quantile predictions.
    horizon : int
        Forecast horizon H.
    interval_pairs : Tuple[str, str] or List[Tuple[str, str]]
        A tuple of column names `(lower_col, upper_col)` or a list of such tuples
        representing quantile prediction pairs generated by the base learner.
        Must strictly follow the `<model>-lo-<level>` and `<model>-hi-<level>`
        naming convention.
    median_cols : Optional[Union[str, List[str]]], default=None
        Optional single column name or list of column names corresponding to median/P50
        model estimates (e.g., `"LGBM"` or `["LGBM", "LGBM-med"]`). If provided,
        `predict_interval()` will output additional `<median_col>-cqr` columns linearly
        interpolated inside the conformal bounds based on the original interval's relative position.
    n_windows : int, default=3
        Number of backtesting windows used to extract calibration residuals.
    alpha : float, default=0.05
        Significance level applied in the regressor (target coverage = 1 - alpha).
    id_col : str, default="unique_id"
        Column name representing the unique identifier for each time series.
    time_col : str, default="ds"
        Column name representing time or timestamp steps.
    target_col : str, default="y"
        Column name representing the target variable.

    Attributes
    ----------
    learner : BaseEstimator
        The base learner employed for time series forecasting.
    horizon : int
        Forecast horizon H.
    interval_pairs_ : List[Tuple[str, str]]
        Normalized and validated list of quantile column pairs.
    median_cols_ : List[str]
        Normalized list of median column names to be adjusted during prediction.
    n_windows : int
        Number of backtesting windows.
    alpha : float
        Significance level.
    id_col : str
        Identifier column name.
    time_col : str
        Time column name.
    target_col : str
        Target column name.
    exog_cols_ : list
        List of detected exogenous column names.
    ncscores_ : dict
        Dictionary mapping each quantile pair key (`"low_col:high_col"`) to a 2D numpy
        array of nonconformity scores of shape (N, horizon).
    n : int, default=0
        Total number of calibration trajectories extracted across windows and series.

    Notes
    -----
    - Nonconformity scores are computed via $E_{i,t} = \max(q_{\text{low}} - y, y - q_{\text{high}})$.
    - Finite-sample quantile adjustment uses level $\lceil (n+1)(1-\alpha) \rceil / n$.

    Examples
    --------
    >>> import lightgbm as lgb
    >>> from mlforecast import MLForecast
    >>> from tinyconformal.timeseries import ConformalQuantileTimeSeriesRegressor
    >>>
    >>> def create_mlforecast_multiquantile():
    ...     models = {
    ...         "LGBM-lo-90": lgb.LGBMRegressor(objective="quantile", alpha=0.05, random_state=42),
    ...         "LGBM-hi-90": lgb.LGBMRegressor(objective="quantile", alpha=0.95, random_state=42),
    ...         "LGBM-lo-50": lgb.LGBMRegressor(objective="quantile", alpha=0.25, random_state=42),
    ...         "LGBM-hi-50": lgb.LGBMRegressor(objective="quantile", alpha=0.75, random_state=42),
    ...     }
    ...     return MLForecast(
    ...         models=models,
    ...         freq="D",
    ...         lags=[1, 7],
    ...     )
    >>>
    >>> base_mlf = create_mlforecast_multiquantile()
    >>> cqr = ConformalQuantileTimeSeriesRegressor(
    ...     learner=base_mlf,
    ...     horizon=7,
    ...     interval_pairs=[
    ...         ("LGBM-lo-90", "LGBM-hi-90"),
    ...         ("LGBM-lo-50", "LGBM-hi-50"),
    ...     ],
    ...     n_windows=5,
    ...     alpha=0.10,
    ... )
    >>> cqr.fit(df)
    >>> predictions = cqr.predict_interval(h=7)
    >>> eval_results = cqr.evaluate(df_test)
    """

    def __init__(
        self,
        learner: BaseEstimator,
        horizon: int,
        interval_pairs: Union[Tuple[str, str], List[Tuple[str, str]]],
        median_cols: Optional[Union[str, List[str]]] = None,
        n_windows: int = 3,
        alpha: float = 0.05,
        id_col: str = "unique_id",
        time_col: str = "ds",
        target_col: str = "y",
    ):
        super().__init__(
            learner=learner,
            horizon=horizon,
            n_windows=n_windows,
            alpha=alpha,
            id_col=id_col,
            time_col=time_col,
            target_col=target_col,
        )
        self.interval_pairs = interval_pairs
        self.interval_pairs_: List[Tuple[str, str]] = self._normalize_interval_pairs(
            interval_pairs
        )
        self.median_cols = median_cols
        self.median_cols_: List[str] = self._normalize_median_cols(median_cols)

    def _parse_quantile_pair(self, low_col: str, high_col: str) -> Dict[str, str]:
        """
        Validates and extracts metadata from a quantile column pair.

        Raises ValueError if column names do not strictly comply with the
        Nixtla/Conformal pattern '<model>-lo-<level>' and '<model>-hi-<level>'.
        """
        QUANTILE_COL_PATTERN = re.compile(
            r"^(?P<model>.+)-(?P<bound>lo|hi)-(?P<level>\d+)$"
        )

        match_low = QUANTILE_COL_PATTERN.match(low_col)
        match_high = QUANTILE_COL_PATTERN.match(high_col)

        if not match_low or match_low.group("bound") != "lo":
            raise ValueError(
                f"Invalid lower quantile column name: '{low_col}'. "
                f"Expected pattern '<model>-lo-<level>' (e.g., 'LGBM-lo-90')."
            )

        if not match_high or match_high.group("bound") != "hi":
            raise ValueError(
                f"Invalid upper quantile column name: '{high_col}'. "
                f"Expected pattern '<model>-hi-<level>' (e.g., 'LGBM-hi-90')."
            )

        model_low, level_low = match_low.group("model"), match_low.group("level")
        model_high, level_high = match_high.group("model"), match_high.group("level")

        if model_low != model_high:
            raise ValueError(
                f"Model name mismatch in quantile pair: '{model_low}' vs '{model_high}'."
            )

        if level_low != level_high:
            raise ValueError(
                f"Coverage level mismatch in quantile pair: '{level_low}' vs '{level_high}'."
            )

        return {
            "model": model_low,
            "level": int(level_low),
        }

    def _normalize_median_cols(
        self, median_cols: Optional[Union[str, List[str]]]
    ) -> List[str]:
        """Normalizes and validates median_cols input into a list of strings."""
        if median_cols is None:
            return []
        if isinstance(median_cols, str):
            return [median_cols]
        if isinstance(median_cols, list) and all(
            isinstance(col, str) for col in median_cols
        ):
            return median_cols

        raise ValueError(
            "median_cols must be a single column name (str), "
            "a list of column names (List[str]), or None."
        )

    def _normalize_interval_pairs(
        self,
        interval_pairs: Union[Tuple[str, str], List[Tuple[str, str]]],
    ) -> List[Tuple[str, str]]:
        """Normalizes and validates interval_pairs input using Regex pattern matching."""
        if isinstance(interval_pairs, tuple) and len(interval_pairs) == 2:
            pairs = [interval_pairs]
        elif isinstance(interval_pairs, list) and all(
            isinstance(p, (tuple, list)) and len(p) == 2 for p in interval_pairs
        ):
            pairs = [tuple(p) for p in interval_pairs]
        else:
            raise ValueError(
                "interval_pairs must be a tuple of 2 column names (low, high) "
                "or a list of such tuples."
            )

        for low_col, high_col in pairs:
            self._parse_quantile_pair(low_col, high_col)

        return pairs

    def _sample_correction(self, alpha: float) -> float:
        """Computes finite-sample quantile adjustment level."""
        q_level = np.ceil((self.n + 1) * (1.0 - alpha)) / self.n
        return float(np.clip(q_level, 0.0, 1.0))

    def _generate_residuals(
        self, q_low: np.ndarray, q_high: np.ndarray, y_true: np.ndarray
    ) -> np.ndarray:
        """Computes CQR Nonconformity Scores: E_{i,t} = max(q_low - y, y - q_high)"""
        return np.maximum(q_low - y_true, y_true - q_high)

    def _sequential_backtesting(
        self,
        df: pd.DataFrame,
        step_size: Optional[int] = None,
        static_features: Optional[list] = None,
    ) -> dict:
        """Executes sequential backtesting across n_windows to extract CQR nonconformity scores."""
        step_size = step_size or self.horizon

        df = df.sort_values(by=[self.id_col, self.time_col]).reset_index(drop=True)
        unique_ids = df[self.id_col].unique()
        n_series = len(unique_ids)

        time_steps = np.sort(df[self.time_col].unique())
        total_steps = len(time_steps)

        required_steps = self.horizon + (self.n_windows - 1) * step_size
        if total_steps <= required_steps:
            raise ValueError(
                f"Time series has {total_steps} unique time steps, but "
                f"n_windows={self.n_windows}, horizon={self.horizon}, step_size={step_size} "
                f"requires at least {required_steps + 1} steps."
            )

        residuals_by_model = {}

        for w in range(self.n_windows):
            val_end_idx = total_steps - w * step_size
            val_start_idx = val_end_idx - self.horizon

            cutoff_time = time_steps[val_start_idx - 1]
            val_times = time_steps[val_start_idx:val_end_idx]

            train_mask = df[self.time_col] <= cutoff_time
            val_mask = df[self.time_col].isin(val_times)

            train_df = df[train_mask].reset_index(drop=True)
            val_df = (
                df[val_mask]
                .sort_values(by=[self.id_col, self.time_col])
                .reset_index(drop=True)
            )

            learner_clone = self._invoke(
                self.learner.fit,
                df=train_df,
                id_col=self.id_col,
                time_col=self.time_col,
                target_col=self.target_col,
                static_features=static_features,
            )

            predict_cols = [self.id_col, self.time_col] + self.exog_cols_
            X_val = val_df[predict_cols] if self.exog_cols_ else None

            fcst = (
                self._invoke(
                    learner_clone.predict,
                    h=self.horizon,
                    X_df=X_val,
                )
                .sort_values(by=[self.id_col, self.time_col])
                .reset_index(drop=True)
            )

            y_true = val_df[self.target_col].to_numpy().reshape(n_series, self.horizon)

            for low_col, high_col in self.interval_pairs_:
                if low_col not in fcst.columns or high_col not in fcst.columns:
                    raise KeyError(
                        f"Columns {(low_col, high_col)} were not found in forecast output. "
                        f"Available columns: {list(fcst.columns)}"
                    )

                q_low = fcst[low_col].to_numpy().reshape(n_series, self.horizon)
                q_high = fcst[high_col].to_numpy().reshape(n_series, self.horizon)

                pair_key = f"{low_col}:{high_col}"
                r = self._generate_residuals(q_low, q_high, y_true)

                if pair_key not in residuals_by_model:
                    residuals_by_model[pair_key] = []
                residuals_by_model[pair_key].append(r)

        return residuals_by_model

    def _compute_bounds(
        self,
        q_low: np.ndarray,
        q_high: np.ndarray,
        pair_key: str,
        h: int,
        n_series: int,
        alpha: Optional[float] = None,
    ) -> Tuple[np.ndarray, np.ndarray]:
        """Computes lower and upper conformalized quantile bounds: [q_low - q_hat, q_high + q_hat]"""
        eff_alpha = self._get_alpha(alpha)
        q_level = self._sample_correction(eff_alpha)

        ncscore = self.ncscores_[pair_key]
        ncscore_sliced = ncscore[:, :h]

        q_hat_h = self._compute_qhat(ncscore_sliced, q_level, axis=0)
        q_hat_tiled = np.tile(q_hat_h, n_series)

        lower_bound = q_low - q_hat_tiled
        upper_bound = q_high + q_hat_tiled

        return lower_bound, upper_bound

    def predict_interval(
        self,
        h: Optional[int] = None,
        alpha: Optional[float] = None,
        X_df: Optional[pd.DataFrame] = None,
    ) -> pd.DataFrame:
        """Applies conformal correction to quantile pairs and interpolates configured medians.

        Generates calibrated interval columns named `<low_col>-cqr` and `<high_col>-cqr`.
        If `median_cols` was specified during initialization, it also outputs `<med_col>-cqr`
        columns scaled according to the original relative skewness ratio.

        Parameters
        ----------
        h : Optional[int], default=None
            Forecast horizon. If None, uses the default horizon from the underlying learner.
        alpha : Optional[float], default=None
            Significance level (1 - coverage rate). If None, uses the value calculated
            during `fit`.
        X_df : Optional[pd.DataFrame], default=None
            Exogenous features DataFrame for the forecast horizon.

        Returns
        -------
        pd.DataFrame
            DataFrame containing raw base predictions, conformal-calibrated interval bounds
            (`<col>-cqr`), and re-scaled median estimates (`<med_col>-cqr`) when applicable.
        """
        alpha = self._get_alpha(alpha)
        h = self._get_horizon(h)

        pred_df = (
            self._invoke(
                self.learner.predict,
                h=h,
                X_df=X_df,
            )
            .sort_values(by=[self.id_col, self.time_col])
            .reset_index(drop=True)
        )

        n_series = pred_df[self.id_col].nunique()

        for low_col, high_col in self.interval_pairs_:
            q_low = pred_df[low_col].to_numpy()
            q_high = pred_df[high_col].to_numpy()
            pair_key = f"{low_col}:{high_col}"

            lower_bound, upper_bound = self._compute_bounds(
                q_low=q_low,
                q_high=q_high,
                pair_key=pair_key,
                h=h,
                n_series=n_series,
                alpha=alpha,
            )

            pred_df[f"{low_col}-cqr"] = lower_bound
            pred_df[f"{high_col}-cqr"] = upper_bound

        if self.median_cols_:
            base_spread = np.maximum(q_high - q_low, 1e-6)
            cqr_spread = np.maximum(upper_bound - lower_bound, 1e-6)

            for med_col in self.median_cols_:
                q_med = pred_df[med_col].to_numpy()
                skew_ratio = np.clip((q_med - q_low) / base_spread, 0.0, 1.0)

                pred_df[f"{med_col}-cqr"] = lower_bound + skew_ratio * cqr_spread

        return pred_df
