# Copyright (c) 2024-2026 Lucas Leão
# TinyConformal - A small toolbox for conformal prediction
# Licensed under the MIT License

from collections.abc import Mapping
from typing import Dict, List, Optional, Tuple, Union
import numpy as np
import pandas as pd
from sklearn.base import BaseEstimator
from .base import BaseConformalTimeSeriesRegressor
import re
from tinyconformal.utils.imports import requires_extra
import copy


class ConformalQuantileTimeSeriesRegressor(BaseConformalTimeSeriesRegressor):
    r"""
    Multi-Step Conformal Quantile Regressor for Time Series (TSCQR).

    Applies Conformalized Quantile Regression (CQR) over multi-step horizons for
    Nixtla-style estimators (e.g., MLForecast or StatsForecast) using sequential
    backtesting to build empirical nonconformity scores across single or multiple
    quantile prediction pairs.

    Column Naming Convention
    ------------------------
    All quantile columns supplied in `intervals` MUST follow the strict pattern:
    - Lower bound: `<model>-lo-<level>` (e.g., `'LGBM-lo-90'`)
    - Upper bound: `<model>-hi-<level>` (e.g., `'LGBM-hi-90'`)

    where `<model>` is the estimator name and `<level>` is an integer representing
    the nominal coverage percentage (e.g., 90 for a 90% prediction interval).

    Output Columns
    --------------
    When calling `predict_interval()`, conformalized lower and upper prediction
    bounds are added as new columns with the `-cqr` suffix attached:
    - `<model>-lo-<level>-cqr`
    - `<model>-hi-<level>-cqr`

    This naming structure allows seamless pattern matching in downstream evaluation
    utilities such as `evaluate()`.

    Parameters
    ----------
    learner : BaseEstimator
        Unfitted base estimator adhering to the Nixtla interface (e.g., MLForecast
        or StatsForecast) configured to generate quantile predictions.
    horizon : int
        Forecast horizon H.
    intervals : tuple, list, or mapping
        A tuple of column names `(lower_col, upper_col)` or a list of such tuples
        representing quantile prediction pairs generated by the base learner.
        To associate an optional median with each pair, pass a dictionary whose keys
        are `(lower_col, upper_col)` tuples and whose values are the median column name
        or `None`.
        Must strictly follow the `<model>-lo-<level>` and `<model>-hi-<level>`
        naming convention.
    n_windows : int, default=3
        Number of backtesting windows used to extract calibration residuals.
    id_col : str, default="unique_id"
        Column name representing the unique identifier for each time series.
    time_col : str, default="ds"
        Column name representing time or timestamp steps.
    target_col : str, default="y"
        Column name representing the target variable.

    Attributes
    ----------
    learner : BaseEstimator
        The base learner employed for time series forecasting.
    horizon : int
        Forecast horizon H.
    intervals_ : List[Tuple[str, str]]
        Normalized and validated list of quantile column pairs.
    interval_medians_ : Dict[Tuple[str, str], Optional[str]]
        Mapping from each normalized interval pair to its optional median column.
    interval_alphas_ : Dict[Tuple[str, str], float]
        Significance level inferred from each pair's coverage suffix. For example,
        columns ending in `-90` use `alpha=0.10`.
    n_windows : int
        Number of backtesting windows.
    alpha : float
        Significance level.
    id_col : str
        Identifier column name.
    time_col : str
        Time column name.
    target_col : str
        Target column name.
    exog_cols_ : list
        List of detected exogenous column names.
    ncscores_ : dict
        Dictionary mapping each quantile pair key (`"low_col:high_col"`) to a 2D numpy
        array of nonconformity scores of shape (N, horizon).
    n : int, default=0
        Total number of calibration trajectories extracted across windows and series.

    Notes
    -----
    - Nonconformity scores are computed via $E_{i,t} = \max(q_{\text{low}} - y, y - q_{\text{high}})$.
    - Finite-sample quantile adjustment uses level $\lceil (n+1)(1-\alpha) \rceil / n$.

    Examples
    --------
    >>> import lightgbm as lgb
    >>> from mlforecast import MLForecast
    >>> from tinyconformal.timeseries import ConformalQuantileTimeSeriesRegressor
    >>>
    >>> def create_mlforecast_multiquantile():
    ...     models = {
    ...         "LGBM-lo-90": lgb.LGBMRegressor(objective="quantile", alpha=0.05, random_state=42),
    ...         "LGBM-hi-90": lgb.LGBMRegressor(objective="quantile", alpha=0.95, random_state=42),
    ...         "LGBM-lo-50": lgb.LGBMRegressor(objective="quantile", alpha=0.25, random_state=42),
    ...         "LGBM-hi-50": lgb.LGBMRegressor(objective="quantile", alpha=0.75, random_state=42),
    ...         "LGBM-50": lgb.LGBMRegressor(objective="quantile", alpha=0.50, random_state=42),
    ...     }
    ...     return MLForecast(
    ...         models=models,
    ...         freq="D",
    ...         lags=[1, 7],
    ...     )
    >>>
    >>> base_mlf = create_mlforecast_multiquantile()
    >>> cqr = ConformalQuantileTimeSeriesRegressor(
    ...     learner=base_mlf,
    ...     horizon=7,
    ...     intervals=[
    ...         ("LGBM-lo-90", "LGBM-hi-90"),
    ...         ("LGBM-lo-50", "LGBM-hi-50"),
    ...     ],
    ...     n_windows=5,
    ... )
    >>> cqr.fit(df)
    >>> predictions = cqr.predict_interval(h=7)
    >>> eval_results = cqr.evaluate(df_test)
    >>> # Medians can be associated with selected intervals while others omit one.
    >>> cqr_with_medians = ConformalQuantileTimeSeriesRegressor(
    ...     learner=base_mlf,
    ...     horizon=7,
    ...     intervals={
    ...         ("LGBM-lo-90", "LGBM-hi-90"): "LGBM-50",
    ...         ("LGBM-lo-50", "LGBM-hi-50"): None,
    ...     },
    ...     n_windows=5,
    ... )
    """

    def __init__(
        self,
        learner: BaseEstimator,
        horizon: int,
        intervals: Union[
            Tuple[str, str],
            List[Tuple[str, str]],
            Mapping[Tuple[str, str], Optional[str]],
        ],
        n_windows: int = 3,
        id_col: str = "unique_id",
        time_col: str = "ds",
        target_col: str = "y",
    ):
        self.intervals = intervals
        (
            self.intervals_,
            self.interval_medians_,
            self.interval_alphas_,
        ) = self._normalize_intervals(intervals)

        # The base class expects one valid alpha during fit. TSCQR prediction and
        # evaluation always use the alpha associated with each configured interval.
        first_alpha = next(iter(self.interval_alphas_.values()))
        super().__init__(
            learner=learner,
            horizon=horizon,
            n_windows=n_windows,
            alpha=first_alpha,
            id_col=id_col,
            time_col=time_col,
            target_col=target_col,
        )

    def _parse_quantile_pair(self, low_col: str, high_col: str) -> Dict[str, str]:
        """
        Validates and extracts metadata from a quantile column pair.

        Raises ValueError if column names do not strictly comply with the
        Nixtla/Conformal pattern '<model>-lo-<level>' and '<model>-hi-<level>'.
        """
        QUANTILE_COL_PATTERN = re.compile(
            r"^(?P<model>.+)-(?P<bound>lo|hi)-(?P<level>\d+)$"
        )

        match_low = QUANTILE_COL_PATTERN.match(low_col)
        match_high = QUANTILE_COL_PATTERN.match(high_col)

        if not match_low or match_low.group("bound") != "lo":
            raise ValueError(
                f"Invalid lower quantile column name: '{low_col}'. "
                f"Expected pattern '<model>-lo-<level>' (e.g., 'LGBM-lo-90')."
            )

        if not match_high or match_high.group("bound") != "hi":
            raise ValueError(
                f"Invalid upper quantile column name: '{high_col}'. "
                f"Expected pattern '<model>-hi-<level>' (e.g., 'LGBM-hi-90')."
            )

        model_low, level_low = match_low.group("model"), match_low.group("level")
        model_high, level_high = match_high.group("model"), match_high.group("level")

        if model_low != model_high:
            raise ValueError(
                f"Model name mismatch in quantile pair: '{model_low}' vs '{model_high}'."
            )

        if level_low != level_high:
            raise ValueError(
                f"Coverage level mismatch in quantile pair: '{level_low}' vs '{level_high}'."
            )

        level = int(level_low)
        if not 0 < level < 100:
            raise ValueError("Coverage level must be an integer between 1 and 99.")

        return {
            "model": model_low,
            "level": level,
        }

    def _normalize_intervals(
        self,
        intervals: Union[
            Tuple[str, str],
            List[Tuple[str, str]],
            Mapping[Tuple[str, str], Optional[str]],
        ],
    ) -> Tuple[
        List[Tuple[str, str]],
        Dict[Tuple[str, str], Optional[str]],
        Dict[Tuple[str, str], float],
    ]:
        """Normalize interval pairs and their optional median-column associations."""
        if isinstance(intervals, Mapping):
            if not all(
                isinstance(pair, tuple) and len(pair) == 2
                for pair in intervals
            ):
                raise ValueError(
                    "intervals dictionary keys must be tuples of 2 column names "
                    "(low, high)."
                )
            invalid_medians = [
                median
                for median in intervals.values()
                if median is not None and not isinstance(median, str)
            ]
            if invalid_medians:
                raise ValueError(
                    "intervals dictionary values must be a median column name "
                    "(str) or None."
                )
            pairs = list(intervals)
            medians = dict(intervals)
        elif isinstance(intervals, tuple) and len(intervals) == 2:
            pairs = [intervals]
            medians = {intervals: None}
        elif isinstance(intervals, list) and all(
            isinstance(p, (tuple, list)) and len(p) == 2 for p in intervals
        ):
            pairs = [tuple(p) for p in intervals]
            medians = {pair: None for pair in pairs}
        else:
            raise ValueError(
                "intervals must be a tuple of 2 column names (low, high) "
                "or a list or dictionary of such tuples."
            )

        if not pairs:
            raise ValueError("intervals must contain at least one quantile pair.")

        alphas = {}
        for low_col, high_col in pairs:
            metadata = self._parse_quantile_pair(low_col, high_col)
            alphas[(low_col, high_col)] = 1.0 - metadata["level"] / 100.0

        configured_medians = [median for median in medians.values() if median is not None]
        if len(configured_medians) != len(set(configured_medians)):
            raise ValueError(
                "Each median column can be associated with only one interval pair."
            )

        return pairs, medians, alphas

    def _sample_correction(self, alpha: float) -> float:
        """Computes finite-sample quantile adjustment level."""
        q_level = np.ceil((self.n + 1) * (1.0 - alpha)) / self.n
        return float(np.clip(q_level, 0.0, 1.0))

    def _generate_residuals(
        self, q_low: np.ndarray, q_high: np.ndarray, y_true: np.ndarray
    ) -> np.ndarray:
        """Computes CQR Nonconformity Scores: E_{i,t} = max(q_low - y, y - q_high)"""
        return np.maximum(q_low - y_true, y_true - q_high)

    def _prepare_and_validate_steps(
        self, df: pd.DataFrame, step_size: int
    ) -> Tuple[np.ndarray, int, int]:
        """Validates if the time series has enough steps for the requested backtesting windows."""
        unique_ids = df[self.id_col].unique()
        n_series = len(unique_ids)

        time_steps = np.sort(df[self.time_col].unique())
        total_steps = len(time_steps)

        required_steps = self.horizon + (self.n_windows - 1) * step_size
        if total_steps <= required_steps:
            raise ValueError(
                f"Time series has {total_steps} unique time steps, but "
                f"n_windows={self.n_windows}, horizon={self.horizon}, step_size={step_size} "
                f"requires at least {required_steps + 1} steps."
            )

        return time_steps, total_steps, n_series

    def _split_train_val_window(
        self,
        df: pd.DataFrame,
        time_steps: np.ndarray,
        total_steps: int,
        w: int,
        step_size: int,
    ) -> Tuple[pd.DataFrame, pd.DataFrame]:
        """Slices the dataframe into training and validation sets for a specific window index."""
        val_end_idx = total_steps - w * step_size
        val_start_idx = val_end_idx - self.horizon

        cutoff_time = time_steps[val_start_idx - 1]
        val_times = time_steps[val_start_idx:val_end_idx]

        train_mask = df[self.time_col] <= cutoff_time
        val_mask = df[self.time_col].isin(val_times)

        train_df = df[train_mask].reset_index(drop=True)
        val_df = (
            df[val_mask]
            .sort_values(by=[self.id_col, self.time_col])
            .reset_index(drop=True)
        )

        return train_df, val_df

    def _fit_predict_window(
        self,
        train_df: pd.DataFrame,
        val_df: pd.DataFrame,
        static_features: Optional[list],
    ) -> pd.DataFrame:
        """Clones the learner, fits it on the training window, and predicts the validation window."""
        learner_clone = copy.deepcopy(self.learner)
        self._invoke(
            learner_clone.fit,
            df=train_df,
            id_col=self.id_col,
            time_col=self.time_col,
            target_col=self.target_col,
            static_features=static_features,
        )

        predict_cols = [self.id_col, self.time_col] + self.exog_cols_
        X_val = val_df[predict_cols] if self.exog_cols_ else None

        fcst = (
            self._invoke(
                learner_clone.predict,
                h=self.horizon,
                X_df=X_val,
            )
            .sort_values(by=[self.id_col, self.time_col])
            .reset_index(drop=True)
        )

        return fcst

    def _compute_window_residuals(
        self,
        fcst: pd.DataFrame,
        val_df: pd.DataFrame,
        n_series: int,
        residuals_by_model: dict,
    ) -> None:
        """Calculates nonconformity scores for the predictions and updates the residuals dictionary."""
        target_pivot = (
            val_df.pivot(
                index=self.id_col, columns=self.time_col, values=self.target_col
            )
            .sort_index(axis=0)
            .sort_index(axis=1)
        )
        y_true = target_pivot.to_numpy()
        if y_true.shape != (n_series, self.horizon) or np.isnan(y_true).any():
            raise ValueError(
                "Each series must contain exactly one target value for every "
                "calibration horizon step."
            )

        for low_col, high_col in self.intervals_:
            if low_col not in fcst.columns or high_col not in fcst.columns:
                raise KeyError(
                    f"Columns {(low_col, high_col)} were not found in forecast output. "
                    f"Available columns: {list(fcst.columns)}"
                )

            quantiles = (
                fcst.pivot(
                    index=self.id_col,
                    columns=self.time_col,
                    values=[low_col, high_col],
                )
                .sort_index(axis=0)
                .sort_index(axis=1, level=1)
            )
            q_low = quantiles[low_col].to_numpy()
            q_high = quantiles[high_col].to_numpy()
            if (
                not quantiles.index.equals(target_pivot.index)
                or q_low.shape != y_true.shape
                or q_high.shape != y_true.shape
                or np.isnan(q_low).any()
                or np.isnan(q_high).any()
            ):
                raise ValueError(
                    "Forecast and target rows are not aligned for every series and "
                    "calibration horizon step."
                )

            pair_key = f"{low_col}:{high_col}"
            r = self._generate_residuals(q_low, q_high, y_true)

            if pair_key not in residuals_by_model:
                residuals_by_model[pair_key] = []
            residuals_by_model[pair_key].append(r)

    def _compute_bounds(
        self,
        q_low: np.ndarray,
        q_high: np.ndarray,
        pair_key: str,
        h: int,
        n_series: int,
        alpha: float,
    ) -> Tuple[np.ndarray, np.ndarray]:
        """Computes lower and upper conformalized quantile bounds.

        The returned bounds are ``q_low - q_hat`` and ``q_high + q_hat``.
        """
        q_level = self._sample_correction(self._get_alpha(alpha))

        ncscore = self.ncscores_[pair_key]
        ncscore_sliced = ncscore[:, :h]

        q_hat_h = self._compute_qhat(ncscore_sliced, q_level, axis=0)
        q_hat_tiled = np.tile(q_hat_h, n_series)

        lower_bound = q_low - q_hat_tiled
        upper_bound = q_high + q_hat_tiled

        return lower_bound, upper_bound

    @requires_extra("series")
    def predict_interval(
        self,
        h: Optional[int] = None,
        X_df: Optional[pd.DataFrame] = None,
    ) -> pd.DataFrame:
        """Applies conformal correction to quantile pairs and interpolates configured medians.

        Generates calibrated interval columns named `<low_col>-cqr` and `<high_col>-cqr`.
        If a median was associated with an interval pair during initialization, it also
        outputs a `<median_col>-cqr` column scaled according to that pair's original
        relative skewness ratio.

        Parameters
        ----------
        h : Optional[int], default=None
            Forecast horizon. If None, uses the default horizon from the underlying learner.
        X_df : Optional[pd.DataFrame], default=None
            Exogenous features DataFrame for the forecast horizon.

        Returns
        -------
        pd.DataFrame
            DataFrame containing raw base predictions, conformal-calibrated interval bounds
            (`<col>-cqr`), and re-scaled median estimates (`<med_col>-cqr`) when applicable.
        """
        h = self._get_horizon(h)
        self._check_is_fitted()

        pred_df = (
            self._invoke(
                self.learner.predict,
                h=h,
                X_df=X_df,
            )
            .sort_values(by=[self.id_col, self.time_col])
            .reset_index(drop=True)
        )

        n_series = pred_df[self.id_col].nunique()

        for low_col, high_col in self.intervals_:
            q_low = pred_df[low_col].to_numpy()
            q_high = pred_df[high_col].to_numpy()
            pair_key = f"{low_col}:{high_col}"
            interval_alpha = self.interval_alphas_[(low_col, high_col)]

            lower_bound, upper_bound = self._compute_bounds(
                q_low=q_low,
                q_high=q_high,
                pair_key=pair_key,
                h=h,
                n_series=n_series,
                alpha=interval_alpha,
            )

            pred_df[f"{low_col}-cqr"] = lower_bound
            pred_df[f"{high_col}-cqr"] = upper_bound

            median_col = self.interval_medians_[(low_col, high_col)]
            if median_col is not None:
                base_spread = np.maximum(q_high - q_low, 1e-6)
                cqr_spread = np.maximum(upper_bound - lower_bound, 1e-6)
                q_median = pred_df[median_col].to_numpy()
                skew_ratio = np.clip(
                    (q_median - q_low) / base_spread, 0.0, 1.0
                )
                pred_df[f"{median_col}-cqr"] = (
                    lower_bound + skew_ratio * cqr_spread
                )

        return pred_df

    @requires_extra("series")
    def evaluate(
        self,
        df_test: pd.DataFrame,
        h: Optional[int] = None,
    ) -> pd.DataFrame:
        """Evaluate every configured raw and conformalized interval at its own alpha."""
        eval_df = self.predict_interval(X_df=df_test, h=h)
        eval_df = eval_df.merge(
            df_test[[self.id_col, self.time_col, self.target_col]],
            on=[self.id_col, self.time_col],
            how="inner",
        )
        if eval_df.empty:
            raise ValueError(
                "No prediction rows matched df_test on the identifier and time columns."
            )

        y_true = eval_df[self.target_col].to_numpy()
        records = []
        for low_col, high_col in self.intervals_:
            metadata = self._parse_quantile_pair(low_col, high_col)
            alpha = self.interval_alphas_[(low_col, high_col)]
            for suffix, model_suffix in (("", ""), ("-cqr", "-cqr")):
                lower = eval_df[f"{low_col}{suffix}"].to_numpy()
                upper = eval_df[f"{high_col}{suffix}"].to_numpy()
                records.append(
                    {
                        "model": f"{metadata['model']}{model_suffix}",
                        "level": f"{metadata['level']}%",
                        "alpha": alpha,
                        "coverage_rate": np.round(
                            self._coverage_rate(y_true, lower, upper), 3
                        ),
                        "interval_width_mean": np.round(
                            self._interval_width_mean(lower, upper), 3
                        ),
                        "mwis": np.round(
                            self._mwi_score(y_true, lower, upper, alpha), 3
                        ),
                    }
                )

        return (
            pd.DataFrame(records)
            .sort_values(by=["model", "level"])
            .reset_index(drop=True)
        )
